# Project 10: Stars and Planets

## Your Information

At the start of each assignment, you will need to provide us your name and the name of the partner you worked with for this assignment (if you had one). Double click on the cell below or click once and hit enter to edit it. Replace "First Last" with your first name and last name. Replace "None" with the first and last name of your partner if you had one for this assignment. We ask for this information so we don't accuse you of cheating when your code looks like your partner's.

Please keep these lines commented so they don't cause an error.

In [1]:
# MY NAME: Hyokyung Kim

# My PARTNER'S NAME: None

## Imports

Every project will begin with some import statements. It's crucial that you run the cell below, otherwise we will not be able to grade your code and provide feedback to you.

In [2]:
# it is considered a good coding practice to place all import statements at the top of the notebook
import csv
import os
import json
from collections import namedtuple
import student_grader
student_grader.initialize(os.getcwd(), "p10")

ModuleNotFoundError: No module named 'student_grader'

## Changes to Feedback Server and Privacy/User Agreement

By using our feedback server, you are consenting to the transmission of your netid and password to authenticate your identity. We assure you that we will not store this information. This process is necessary for accessing feedback from our LLM system and is conducted in compliance with FERPA regulations.

We will make every effort to keep the feedback server operational for the remainder of the semester.

To receive assistance from our LLM feedback system, you will need to provide your netid and password the first time you run a grader check cell with `should_get_llm_feedback=True`. Your credentials will be sent securely to our feedback server solely for authentication purposes. Upon successful authentication, you will receive a token that allows you to receive feedback without logging in again. This token will expire in 5 hours, after which you will need to log in again to continue using the feedback service.

If you have any questions or concerns about data privacy and security, please make a post on Piazza.

## Learning Objectives

In this project, you will demonstrate how to:

* use `os` module to get information of files in a directory,
* use `os` module to get paths of files,
* look up data between JSON and CSV files using unique keys,
* read JSON and CSV files to store data to `namedTuple` objects,
* clean up missing values and handle cases when the file is too corrupt to parse,

<h2 style="color:red">Warning (Note on Academic Misconduct):</h2>

**IMPORTANT**: **P10 and P11 are two parts of the same data analysis.** You **cannot** switch project partners between these two projects. That is if you partner up with someone for P10, you have to sustain that partnership until the end of P11. Be careful not to work with more than one partner. If you work with a partner on the lab portion, you are **not** allowed to finish your project with a different partner. You may either continue to work with the same partner, or work on P10 and P11 alone. Now may be a good time to review [our course policies](https://cs220.cs.wisc.edu/f24/syllabus.html).

Under any circumstances, **no more than two students are allowed to work together on a project** as mentioned in the course policies. If your code is flagged by our code similarity detection tools, **both partners will be responsible** for sharing/copying the code, even if the code is shared/copied by one of the partners with/from other non-partner student(s). Note that each case of plagiarism will be reported to the Dean of Students with a zero grade on the project. **If you think that someone cannot be your project partner then don’t make that student your lab partner.**

Note that this assignment is longer than previous ones and will take more time to complete.

## Setup:

**Warning:** You need to make sure that the project files are stored in the following structure:

```
+-- p10.ipynb
+-- ... (other files)
+-- small_data
|   +-- mapping_1.json
|   +-- mapping_2.json
|   +-- mapping_3.json
|   +-- planets_1.csv
|   +-- planets_2.csv
|   +-- planets_3.csv
|   +-- stars_1.csv
|   +-- stars_2.csv
|   +-- stars_3.csv
```

## Introduction to Data

### Background:

In P10 and P11, we will be studying stars and planets outside our Solar System using this dataset from the [NASA Exoplanet Archive](https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblView/nph-tblView?app=ExoTbls&config=PSCompPars). We will use Python to ask some interesting questions about the laws of the universe and explore the habitability of other planets in our universe.

In the lab portion, you will work with a small subset of the full dataset. You can find these files inside the `small_data` directory. The full dataset used in P10 and P11 is stored in the same format, so you can then use this code to parse the dataset in P10 and P11.

### Stars:

You can open each of the files inside the `small_data` directory using the file viewer in Jupyter lab (or Microsoft Excel or some other Spreadsheet viewing software) to see how the data is stored. For example, these are the contents of the file `stars_1.csv`:

|Star Name|Spectral Type|Stellar Effective Temperature [K]|Stellar Radius [Solar Radius]|Stellar Mass [Solar mass]|Stellar Luminosity [log(Solar)]|Stellar Surface Gravity [log10(cm/s**2)]|Stellar Age [Gyr]|
|----|-------------|---------------------------------|-----------------------------|-------------------------|-------------------------------|----------------------------------------|-----------------|
|55 Cnc|G8V|5172.00|0.94|0.91|-0.197|4.43|10.200|
|DMPP-1|F8V|6196.00|1.26|1.21|0.320|4.41|2.010|
|GJ 876|M2.5V|3271.00|0.30|0.32|-1.907|4.87|1.000|

As you might have already guessed, this file contains data on a number of *stars* outside our solar system along with some important statistics about these stars. The columns here are as follows:

- `Star Name`: The **name** given to the star by the *International Astronomical Union*,
- `Spectral Type`: The **Spectral Classification** of the star as per the *Morgan–Keenan (MK) system*,
- `Stellar Effective Temperature [K]`: The **temperature** of a *black body* (in units of Kelvin) that would emit the *observed radiation* of the star,
- `Stellar Radius [Solar Radius]`: The **radius** of the star (in units of the radius of the Sun),
- `Stellar Mass [Solar mass]`: The **mass** of the star (in units of the mass of the Sun), **NOTE** that mass is not capitalized in the attribute name,
- `Stellar Luminosity [log(Solar)]`: The *total* amount of **energy radiated** by the star **each second** (represented by the logarithm of the energy radiated by the Sun in each second),
- `Stellar Surface Gravity [log10(cm/s**2)]`: The **acceleration due to the gravity** of the Star at its *surface* (represented by the logarithm of the acceleration measured in centimeter per second squared),
- `Stellar Age [Gyr]`: The total **age** of the star (in units of Giga years, i.e., billions of years).

The two other files `stars_2.csv`, and `stars_3.csv` also store similar data in the same format. At this stage, it is alright if you do not understand what these columns mean - they will be explained to you when they become necessary (in P10 and P11).

### Planets:

On the other hand, here are the contents of the file `planets_1.csv`:

|Planet Name|Discovery Method|Discovery Year|Controversial Flag|Orbital Period [days]|Planet Radius [Earth Radius]|Planet Mass [Earth Mass]|Orbit Semi-Major Axis [au]|Eccentricity|Equilibrium Temperature [K]|Insolation Flux [Earth Flux]|
|-----------|----------------|--------------|------------------|---------------------|----------------------------|------------------------|---------------------------|------------|---------------------------|----------------------------|
|55 Cnc b|Radial Velocity|1996|0|14.65160000|13.900|263.97850|0.113400|0.000000|700||
|55 Cnc c|Radial Velocity|2004|0|44.39890000|8.510|54.47380|0.237300|0.030000|||
|DMPP-1 b|Radial Velocity|2019|0|18.57000000|5.290|24.27000|0.146200|0.083000|877||
|GJ 876 b|Radial Velocity|1998|0|61.11660000|13.300|723.22350|0.208317|0.032400|||
|GJ 876 c|Radial Velocity|2000|0|30.08810000|14.000|226.98460|0.129590|0.255910|||


This file contains data on a number of *planets* outside our solar system along with some important statistics about these planets. The columns here are as follows:

- `Planet Name`: The **name** given to the planet by the *International Astronomical Union*,
- `Discovery Method`: The **method** by which the planet was *discovered*,
- `Discovery Year`: The **year** in which the planet was *discovered*,
- `Controversial Flag`: Indicates whether the status of the discovered object as a planet was **disputed** at the time of discovery, 
- `Orbital Period [days]`: The amount of **time** (in units of days) it takes for the planet to **complete one orbit** around its star,
- `Planet Radius [Earth Radius]`: The **radius** of the planet (in units of the radius of the Earth),
- `Planet Mass [Earth Mass]`: The **mass** of the planet (in units of the mass of the Earth),
- `Orbit Semi-Major Axis [au]`: The **semi-major axis** of the planet's elliptical **orbit** around its host star (in units of Astronomical Units),
- `Eccentricity`: The **eccentricity** of the planet's orbit around its host star,
- `Equilibrium Temperature [K]`: The **temperature** of the planet (in units of Kelvin) if it were a *black body* heated only by its host star,
- `Insolation Flux [Earth Flux]`:  The amount of **radiation** the planet received from its host star **per unit of area** (in units of the Insolation Flux of the Earth from the Sun).

The two other files `planets_2.csv`, and `planets_3.csv` also store similar data in the same format.

### Mapping:

Finally, if you take a look at `mapping_1.json` (you can open json files using any Text Editor), you will see that the file looks like this:

```python
{"55 Cnc b":"55 Cnc","55 Cnc c":"55 Cnc","DMPP-1 b":"DMPP-1","GJ 876 b":"GJ 876","GJ 876 c":"GJ 876"}
```

This file contains a *mapping* from each *planet* in `planets_1.csv` to the *star* in `stars_1.csv` that the planet orbits. Similarly, `mapping_2.json` contains a *mapping* from each *planet* in `planets_2.csv` to the *star* in `stars_2.csv` that the planet orbits, and `mapping_3.json` contains a *mapping* from each *planet* in `planets_3.csv` to the *star* in `stars_3.csv` that the planet orbits.

## Lab Portion (37 Questions)

### Segment 1: File handling with the `os` module

In this segment, you will learn how to use the `os` module effectively.

#### Lab Question 1: List **all** the files and directories in the directory `small_data` using the `os.listdir` function.

Your output **must** be a **list** of **strings**. The order does **not** matter.

Points possible: 3.0

In [3]:
# we have done this one for you
all_files = os.listdir('small_data')

all_files

FileNotFoundError: [Errno 2] No such file or directory: 'small_data'

In [4]:
student_grader.check("lab-q1", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q1...
Great job! You passed all test cases for this question.


True

**Important Warning:** That appeared to work just fine, but you should be **very careful** when using the `os` module. You might have noticed that there are files and directories in the list returned by `os.listdir` that **begin** with the character `"."` (specifically in this case, the file `".DS_Store"` and the directory `".ipynb_checkpoints"`). Such files and directories are used by some operating systems to store metadata. These files are not actually a part of your dataset, and must be **ignored**. 

When you are processing the files in any directory, you **must** always **ignore** such files that begin with the character `"."`, as they are not actually files in the directory. You **must** do this every time you use `os.listdir`.

#### Lab Question 2: List **all** the files and directories in the directory `small_data` that do **not** **start with** the character`"."`.

Your output **must** be a **list** of **strings**. The order does **not** matter.

Points possible: 3.0

In [5]:
# compute and store the answer in the variable 'actual_files', then display it
import os
all_files = os.listdir('small_data')

actual_files = [file for file in all_files if not file.startswith('.')]

actual_files

['mapping_3.json',
 'mapping_2.json',
 'planets_2.csv',
 'planets_3.csv',
 'planets_1.csv',
 'stars_3.csv',
 'stars_2.csv',
 'stars_1.csv',
 'mapping_1.json']

In [6]:
student_grader.check("lab-q2", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q2...
Great job! You passed all test cases for this question.


True

<h4 style="color:red">Important Warning:</h4>

Look at the order in which the files in the **list** `actual_files` are stored. The **ordering** of the files in the **list** returned by `os.listdir` **depends on the operating system**. This means that if you run this code on a **different OS**, the files might be sorted in a **different order**.

For example, if you are using Windows, the variable `actual_files` will likely hold the value:
```python
['mapping_1.json',
 'mapping_2.json',
 'mapping_3.json',
 'planets_1.csv',
 'planets_2.csv',
 'planets_3.csv',
 'stars_1.csv',
 'stars_2.csv',
 'stars_3.csv']
```

but if you are using MacOS, the variable `actual_files` will likely hold the value:
```python
['stars_3.csv',
 'stars_2.csv',
 'stars_1.csv',
 'planets_3.csv',
 'planets_2.csv',
 'planets_1.csv',
 'mapping_3.json',
 'mapping_2.json',
 'mapping_1.json']
```

As you can imagine, this makes `os.listdir` a little **dangerous** because you could write something like `actual_files[0]` in your code, and it will always work the same way on your computer, but will **behave differently on another computer**. To avoid these issues, you should make sure that you always **explicitly sort** the output of `os.listdir` before you use it. This will ensure that the ordering remains consistent across all operating systems.

#### Lab Question 3: List **all** the files and directories in the directory `small_data` that do **not** **start with** the character`"."`, sorted in **reverse alphabetical order**.

Your output **must** be a **list** of **strings**, sorted in **reverse alphabetical** order.

Points possible: 3.0

In [7]:
# compute and store the answer in the variable 'files_in_small_data', then display it
import os
all_files = os.listdir('small_data')
actual_files = [file for file in all_files if not file.startswith('.')]

files_in_small_data = sorted(actual_files, reverse = True)

files_in_small_data

['stars_3.csv',
 'stars_2.csv',
 'stars_1.csv',
 'planets_3.csv',
 'planets_2.csv',
 'planets_1.csv',
 'mapping_3.json',
 'mapping_2.json',
 'mapping_1.json']

In [8]:
student_grader.check("lab-q3", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q3...
Great job! You passed all test cases for this question.


True

#### Lab Question 4: What is the **path** of the file `stars_1.csv` in the directory `small_data`.

You are **allowed** to 'hardcode' the strings `'small_data'` and `'stars_1.csv'` to answer this question.

**Warnings:**

1. You **must not** hardcode the **absolute path** of any file in your code. For instance, the **absolute path** of this file `stars_1.csv` could be: `C:\Users\mdoescher\cs220\p10\small_data\stars_1.csv` (this file path could be slightly different depending on how you organize your files for the class). However, if you hardcode this path in your code, it will **only work on your computer**. In this case, since the notebook `p10.ipynb` is stored in the path `C:\Users\mdoescher\cs220\p10`, the **relative path** of the file is `small_data\stars_1.csv`, and this is the path that **must** be used, if you want your code to work on all computers.
2. You **must not** hardcode either the character `"\"` or the character `"/"` in your paths. If you do so, your code will **crash** when it runs on a **different operating system**. You **must** use the `os.path.join` function to create path strings.

Points possible: 3.0

In [9]:
# we have done this one for you
stars_1_path = os.path.join("small_data", "stars_1.csv")

stars_1_path

'small_data/stars_1.csv'

In [10]:
student_grader.check("lab-q4", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q4...
Great job! You passed all test cases for this question.


True

#### Lab Question 5: List the **paths** of **all** the files in the directory `small_data`.

Your output **must** be a **list** of **strings**. You must **ignore** files that **start with** the character`"."`. The order of the files does **not matter**.

**Warnings:**

1. You **must not** hardcode the **absolute path** of any file in your code. You must use the **relative path** of the files.
2. You **must not** hardcode either the character `"\"` or the character `"/"` in your paths. You **must** use the `os.path.join` function to create paths.

You should use files_in_small_data in your answer.

Points possible: 3.0

In [11]:
# compute and store the answer in the variable 'paths_in_small_data_unsorted', then display it
import os
all_files = os.listdir('small_data')
actual_files = [file for file in all_files if not file.startswith('.')]
files_in_small_data = sorted(actual_files, reverse = True)

paths_in_small_data_unsorted = [os.path.join("small_data", file) for file in actual_files]

paths_in_small_data_unsorted

['small_data/mapping_3.json',
 'small_data/mapping_2.json',
 'small_data/planets_2.csv',
 'small_data/planets_3.csv',
 'small_data/planets_1.csv',
 'small_data/stars_3.csv',
 'small_data/stars_2.csv',
 'small_data/stars_1.csv',
 'small_data/mapping_1.json']

In [12]:
student_grader.check("lab-q5", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q5...
Great job! You passed all test cases for this question.


True

<h4 style="color:red">Important Warning:</h4>

You are not done yet! We have already seen that while using the output of `os.listdir`, you must **sort** the output before using that data. However, you must be **extra careful** while sorting **lists of paths**. To see what could go wrong with sorting, run the following cell:

In [13]:
windows_files = ['small_data\\10\\stars_1.csv', 'small_data\\1\\stars_2.csv']
mac_files = ['small_data/10/stars_1.csv', 'small_data/1/stars_2.csv']
print(sorted(windows_files, reverse=True))
print(sorted(mac_files, reverse=True))

['small_data\\1\\stars_2.csv', 'small_data\\10\\stars_1.csv']
['small_data/10/stars_1.csv', 'small_data/1/stars_2.csv']


As you can see, depending on whether the path separator is `//` or `\`, even the outcome of sorting can **change**. In other words, **depending on your OS**, even the **output of the sorting may be different**. To get around this difficulty, you may use the `split` function to **split** the path by the path separator `os.path.sep`, before sorting.

Run the following cell and figure out what it does:

In [14]:
for path in paths_in_small_data_unsorted:
    print(path.split(os.path.sep))

['small_data', 'mapping_3.json']
['small_data', 'mapping_2.json']
['small_data', 'planets_2.csv']
['small_data', 'planets_3.csv']
['small_data', 'planets_1.csv']
['small_data', 'stars_3.csv']
['small_data', 'stars_2.csv']
['small_data', 'stars_1.csv']
['small_data', 'mapping_1.json']


You can therefore use the `str.split(os.path.sep)` function as a **key** to your `sorted` (or `str.sort`) function to avoid these issues, as in the example below:

#### Lab Question 6: Sort the variable `paths_in_small_data_unsorted` in **reverse alphabetical order** after **splitting** the paths by the **path separator**.

Points possible: 3.0

In [15]:
# we have done this one for you

# the lambda function passed as the `key` here will ensure that before we sort the paths in the list,
# they are split by the path separator; this ensures that the sorting will produce identical outputs
# across different operating systems
paths_in_small_data = sorted(paths_in_small_data_unsorted, key = lambda path: path.split(os.path.sep), reverse=True)

paths_in_small_data

['small_data/stars_3.csv',
 'small_data/stars_2.csv',
 'small_data/stars_1.csv',
 'small_data/planets_3.csv',
 'small_data/planets_2.csv',
 'small_data/planets_1.csv',
 'small_data/mapping_3.json',
 'small_data/mapping_2.json',
 'small_data/mapping_1.json']

In [16]:
student_grader.check("lab-q6", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q6...
Great job! You passed all test cases for this question.


True

#### Lab Question 7: List the **paths** of **all** the JSON files in the directory `small_data`.

Your output **must** be a **list** of **strings**. You must **ignore** files that **start with** the character`"."`, and your output **must** sorted in **reverse alphabetical order**.

**Hint:** You can identify the JSON files as the files which end with the string `".json"`.

Points possible: 3.0

In [17]:
# compute and store the answer in the variable 'json_paths', then display it
json_paths = [path for path in paths_in_small_data if path.endswith(".json")]

json_paths

['small_data/mapping_3.json',
 'small_data/mapping_2.json',
 'small_data/mapping_1.json']

In [18]:
student_grader.check("lab-q7", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q7...
Great job! You passed all test cases for this question.


True

#### Lab Question 8: List the **paths** of **all** the files in the directory `small_data`, whose filename starts with `"stars"`.

Your output **must** be a **list** of **strings**. You must **ignore** files that **start with** the character`"."`, and your output **must** be sorted in **reverse alphabetical order** after **splitting** the paths by the **path separator**.

Points possible: 3.0

In [19]:
# compute and store the answer in the variable 'stars_paths', then display it
stars_paths = [path for path in paths_in_small_data if os.path.basename(path).startswith("stars")]

stars_paths

['small_data/stars_3.csv', 'small_data/stars_2.csv', 'small_data/stars_1.csv']

In [20]:
student_grader.check("lab-q8", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q8...
Great job! You passed all test cases for this question.


True

### Segment 2: Creating Namedtuples

In P10, you will be reading the data in files similar to `stars_1.csv`, `stars_2.csv`, and `stars_3.csv`, and storing the data as a **dictionary** of **named tuples**. Now would be a great time to practice creating similar data structues.

### Data Structure 1: namedtuple `Star`

We will now create a new `Star` type (using `namedtuple`). It **must** have the following attributes:

* `spectral_type`,
* `stellar_effective_temperature`,
* `stellar_radius`,
* `stellar_mass`,
* `stellar_luminosity`,
* `stellar_surface_gravity`,
* `stellar_age`.

In [21]:
# we have done this one for you

# define the list of attributes we want in our namedtuple
star_attributes = ['spectral_type',
                  'stellar_effective_temperature',
                  'stellar_radius',
                  'stellar_mass',
                  'stellar_luminosity',
                  'stellar_surface_gravity',
                  'stellar_age']

# create the namedtuple type 'Star' with the correct attributes
Star = namedtuple("Star", star_attributes)

#### Create a `Star` nametuple.

Let us now test whether we have defined the namedtuple properly by creating a `Star` object.

Points possible: 3.0

In [22]:
# we have done this one for you

sun = Star('G2 V', 5780.0, 1.0, 1.0, 0.0, 4.44, 4.6)

sun

Star(spectral_type='G2 V', stellar_effective_temperature=5780.0, stellar_radius=1.0, stellar_mass=1.0, stellar_luminosity=0.0, stellar_surface_gravity=4.44, stellar_age=4.6)

In [23]:
student_grader.check("lab-star", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-star...
Great job! You passed all test cases for this question.


True

### Segment 3.1: Creating `Star` objects

Now that we have created the `Star` namedtuple, our next objective will be to read the files `stars_1.csv`, `stars_2.csv`, and `stars_3.csv` and create `Star` objects out of all the stars in there. In order to process the CSV files, you will first need to use the `process_csv` function you have been using since P6.

In [24]:
# process_csv file from previous projects here
def process_csv(filename):
    example_file = open(filename, encoding="utf-8")
    example_reader = csv.reader(example_file)
    example_data = list(example_reader)
    example_file.close()
    return example_data

You are now ready to read the data in `stars_1.csv` using `process_csv` and convert the data into `Star` objects. In the cell below, you **must** read the data in `stars_1.csv` and extract the **header** and the non-header **rows** of the file.

In [25]:
# replace the ... with your code
stars_1_csv = process_csv(os.path.join("small_data", "stars_1.csv")) # read the data in 'stars_1.csv'
stars_header = stars_1_csv[0]
stars_1_rows = stars_1_csv[1:]

If you wish to **verify** that you have read the file and defined the variables correctly, you can check that `stars_header` has the value:

```python
['Star Name', 'Spectral Type', 'Stellar Effective Temperature [K]', 'Stellar Radius [Solar Radius]', 
 'Stellar Mass [Solar mass]', 'Stellar Luminosity [log(Solar)]', 'Stellar Surface Gravity [log10(cm/s**2)]',
 'Stellar Age [Gyr]']
```

and that `stars_1_rows` has the value:

```python
[['55 Cnc', 'G8V', '5172.00', '0.94', '0.91', '-0.197', '4.43', '10.200'],
 ['DMPP-1', 'F8V', '6196.00', '1.26', '1.21', '0.320', '4.41', '2.010'],
 ['GJ 876', 'M2.5V', '3271.00', '0.30', '0.32', '-1.907', '4.87', '1.000']]
```

#### Lab Question 9: Create a `Star` object for the **first** star in `"stars_1.csv"`.

The **attribute** of the `Star` namedtuple object, the corresponding **column** of the `stars_1.csv` file where the value should be obtained from, and the correct **data type** for the value are listed in the table below:

|Attribute of `Star` object|Column of `stars_1.csv`|Data Type|
|---------|------|---------|
|`spectral_type`|Spectral Type|**string**|
|`stellar_effective_temperature`|Stellar Effective Temperature [K]|**float**|
|`stellar_radius`|Stellar Radius [Solar Radius]|**float**|
|`stellar_mass`|Stellar Mass [Solar mass]|**float**|
|`stellar_luminosity`|Stellar Luminosity [log(Solar)]|**float**|
|`stellar_surface_gravity`|Stellar Surface Gravity [log10(cm/s**2)]|**float**|
|`stellar_age`|Stellar Age [Gyr]|**float**|

Points possible: 3.0

In [26]:
# replace the ... with your code
row_idx = 0 # the index of the star we want to convert into a Star object

# extract the values from stars_1_rows
spectral_type = stars_1_rows[row_idx][stars_header.index("Spectral Type")] # stars_1_rows[row_idx][stars_header.index(...)]
stellar_effective_temperature = float(stars_1_rows[row_idx][stars_header.index("Stellar Effective Temperature [K]")]) #float(stars_1_rows[row_idx][stars_header.index(...)])
stellar_radius = float(stars_1_rows[row_idx][stars_header.index("Stellar Radius [Solar Radius]")])
stellar_mass = float(stars_1_rows[row_idx][stars_header.index("Stellar Mass [Solar mass]")])
stellar_luminosity = float(stars_1_rows[row_idx][stars_header.index("Stellar Luminosity [log(Solar)]")])
stellar_surface_gravity = float(stars_1_rows[row_idx][stars_header.index("Stellar Surface Gravity [log10(cm/s**2)]")])
stellar_age = float(stars_1_rows[row_idx][stars_header.index("Stellar Age [Gyr]")])

# initialize 'first_star'
first_star = Star(spectral_type, stellar_effective_temperature, stellar_radius, \
                  stellar_mass, stellar_luminosity, \
                  stellar_surface_gravity, stellar_age)

first_star

Star(spectral_type='G8V', stellar_effective_temperature=5172.0, stellar_radius=0.94, stellar_mass=0.91, stellar_luminosity=-0.197, stellar_surface_gravity=4.43, stellar_age=10.2)

In [27]:
student_grader.check("lab-q9", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q9...
Great job! You passed all test cases for this question.


True

#### Lab Question 10: Create a `Star` object for the **second** star in `"stars_1.csv"`.

You **must** create the `Star` object similarly to what you did in the previous question.

Points possible: 3.0

In [28]:
# compute and store the answer in the variable 'second_star', then display it
row_idx = 1 # the index of the star we want to convert into a Star object

spectral_type = stars_1_rows[row_idx][stars_header.index("Spectral Type")] # stars_1_rows[row_idx][stars_header.index(...)]
stellar_effective_temperature = float(stars_1_rows[row_idx][stars_header.index("Stellar Effective Temperature [K]")]) #float(stars_1_rows[row_idx][stars_header.index(...)])
stellar_radius = float(stars_1_rows[row_idx][stars_header.index("Stellar Radius [Solar Radius]")])
stellar_mass = float(stars_1_rows[row_idx][stars_header.index("Stellar Mass [Solar mass]")])
stellar_luminosity = float(stars_1_rows[row_idx][stars_header.index("Stellar Luminosity [log(Solar)]")])
stellar_surface_gravity = float(stars_1_rows[row_idx][stars_header.index("Stellar Surface Gravity [log10(cm/s**2)]")])
stellar_age = float(stars_1_rows[row_idx][stars_header.index("Stellar Age [Gyr]")])

# initialize 'second_star'
second_star = Star(spectral_type, stellar_effective_temperature, stellar_radius, \
                  stellar_mass, stellar_luminosity, \
                  stellar_surface_gravity, stellar_age)

second_star

Star(spectral_type='F8V', stellar_effective_temperature=6196.0, stellar_radius=1.26, stellar_mass=1.21, stellar_luminosity=0.32, stellar_surface_gravity=4.41, stellar_age=2.01)

In [29]:
student_grader.check("lab-q10", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q10...
Great job! You passed all test cases for this question.


True

#### Lab Question 11: What is the `spectral_type` of the **second** star in `"stars_1.csv"`?

You **must** answer this question by accessing the correct **attribute** of the `Star` object `second_star`.

Points possible: 3.0

In [30]:
# we have done this one for you

second_star_spectral_type = second_star.spectral_type

second_star_spectral_type

'F8V'

In [31]:
student_grader.check("lab-q11", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q11...
Great job! You passed all test cases for this question.


True

#### Lab Question 12: What is the `stellar_age` of the **first** star in `"stars_1.csv"`?

You **must** answer this question by accessing the correct **attribute** of the `Star` object `first_star`.|

Points possible: 3.0

In [32]:
# compute and store the answer in the variable 'first_star_stellar_age', then display it
first_star_stellar_age = first_star.stellar_age

first_star_stellar_age

10.2

In [33]:
student_grader.check("lab-q12", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q12...
Great job! You passed all test cases for this question.


True

#### Lab Question 13: What is the **ratio** of the `stellar_radius` of the **first** star in `"stars_1.csv"` to the **second** star in `"stars_1.csv"`?

You **must** answer this question by accessing the correct **attribute** of the `Star` objects `first_star` and `second_star`. 

Points possible: 3.0

In [34]:
# compute and store the answer in the variable 'stellar_radius_ratio', then display it
stellar_radius_ratio = first_star.stellar_radius / second_star.stellar_radius

stellar_radius_ratio

0.7460317460317459

In [35]:
student_grader.check("lab-q13", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q13...
Great job! You passed all test cases for this question.


True

#### Lab Question 14: Create a **dictionary** mapping the `name` of each star in `"stars_1.csv"` to its `Star` object.

Your output **must** look like this:
```python
{'55 Cnc': Star(spectral_type='G8V', stellar_effective_temperature=5172.0, stellar_radius=0.94, 
                stellar_mass=0.91, stellar_luminosity=-0.197, stellar_surface_gravity=4.43, stellar_age=10.2),
 'DMPP-1': Star(spectral_type='F8V', stellar_effective_temperature=6196.0, stellar_radius=1.26, 
                stellar_mass=1.21, stellar_luminosity=0.32, stellar_surface_gravity=4.41, stellar_age=2.01),
 'GJ 876': Star(spectral_type='M2.5V', stellar_effective_temperature=3271.0, stellar_radius=0.3, 
                stellar_mass=0.32, stellar_luminosity=-1.907, stellar_surface_gravity=4.87, stellar_age=1.0)}
```

Points possible: 3.0

In [36]:
# replace the ... with your code

stars_1_dict = {} # initialize empty dictionary to store all stars

for row_idx in range(len(stars_1_rows)):
    star_name = stars_1_rows[row_idx][stars_header.index("Star Name")] #stars_1_rows[row_idx][stars_header.index(...)]
    spectral_type = stars_1_rows[row_idx][stars_header.index("Spectral Type")]
    stellar_effective_temperature = float(stars_1_rows[row_idx][stars_header.index("Stellar Effective Temperature [K]")])
    # extract the other columns from 'stars_1_rows'
    stellar_radius = float(stars_1_rows[row_idx][stars_header.index("Stellar Radius [Solar Radius]")])
    stellar_mass = float(stars_1_rows[row_idx][stars_header.index("Stellar Mass [Solar mass]")])
    stellar_luminosity = float(stars_1_rows[row_idx][stars_header.index("Stellar Luminosity [log(Solar)]")])
    stellar_surface_gravity = float(stars_1_rows[row_idx][stars_header.index("Stellar Surface Gravity [log10(cm/s**2)]")])
    stellar_age = float(stars_1_rows[row_idx][stars_header.index("Stellar Age [Gyr]")])

    star = Star(spectral_type, stellar_effective_temperature, stellar_radius, \
                  stellar_mass, stellar_luminosity, \
                  stellar_surface_gravity, stellar_age) # initialize the 'Star' object using the variables defined above
    stars_1_dict[star_name] = star

stars_1_dict

{'55 Cnc': Star(spectral_type='G8V', stellar_effective_temperature=5172.0, stellar_radius=0.94, stellar_mass=0.91, stellar_luminosity=-0.197, stellar_surface_gravity=4.43, stellar_age=10.2),
 'DMPP-1': Star(spectral_type='F8V', stellar_effective_temperature=6196.0, stellar_radius=1.26, stellar_mass=1.21, stellar_luminosity=0.32, stellar_surface_gravity=4.41, stellar_age=2.01),
 'GJ 876': Star(spectral_type='M2.5V', stellar_effective_temperature=3271.0, stellar_radius=0.3, stellar_mass=0.32, stellar_luminosity=-1.907, stellar_surface_gravity=4.87, stellar_age=1.0)}

In [37]:
student_grader.check("lab-q14", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q14...
Great job! You passed all test cases for this question.


True

#### Lab Question 15: What is the `Star` object of the star (in `stars_1.csv`) named *GJ 876*?

You **must** access the `Star` object in `stars_1_dict` **dictionary** defined above to answer this question.

Points possible: 2.0

In [38]:
# compute and store the answer in the variable 'gj_876', then display it
gj_876 = stars_1_dict["GJ 876"]

gj_876

Star(spectral_type='M2.5V', stellar_effective_temperature=3271.0, stellar_radius=0.3, stellar_mass=0.32, stellar_luminosity=-1.907, stellar_surface_gravity=4.87, stellar_age=1.0)

In [39]:
student_grader.check("lab-q15", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q15...
Great job! You passed all test cases for this question.


True

#### Lab Question 16: What is the `stellar_luminosity` of the star (in `stars_1.csv`) named *GJ 876*?

You **must** access the `Star` object in `stars_1_dict` **dictionary** defined above to answer this question.

Points possible: 2.0

In [40]:
# compute and store the answer in the variable 'gj_876_luminosity', then display it
gj_876_luminosity = stars_1_dict["GJ 876"].stellar_luminosity

gj_876_luminosity

-1.907

In [41]:
student_grader.check("lab-q16", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q16...
Great job! You passed all test cases for this question.


True

### Segment 3.2: Data Cleaning - missing data

We have already parsed the data in `stars_1.csv`. We are now ready to parse the data in **all** the star files of the `small_data` directory. However, there is one minor inconvenience - there is some missing data in `stars_2.csv` and `stars_3.csv`. For example, this is the **first** row of `stars_2.csv`:

```python
['HD 158259', 'G0', '5801.89', '1.21', '1.08', '0.212', '4.25', '']
```

As you can see, the value of the last column (`Stellar Age [Gyr]`) is `''`, which means that the data is missing. When the data is missing, we will want the value of the corresponding attribute in the `Star` object to be `None`.

So, for example, if we are to convert the row above to be a `Star` object, it should look like:

```python
Star(spectral_type='G0', stellar_effective_temperature=5801.89, stellar_radius=1.21, stellar_mass=1.08,
     stellar_luminosity=0.212, stellar_surface_gravity=4.25, stellar_age=None)
```

### Lab Function 1: `star_cell(row_idx, col_name, stars_rows, header=stars_header)`

Since we need to clean the values of the **list** of **lists** `stars_rows` before we can create our required data structure (**dictionary** mapping **strings** to `Star` objects), now would be a good time to create a function that takes in a `row_idx`, a `col_name` and a **list** of **lists** `stars_rows` (as well as the optional argument `header`) and returns the value of the column `col_name` at the row `row_idx`.

This function **must** typecast the values it returns based on the `col_name`. If the value in `stars_rows` is missing (i.e., it is `''`), then the value returned **must** be `None`.

Recall that the **column** of `stars_rows` where the value should be obtained from, and the correct **data type** for the value are listed in the table below:

|Column of `stars_rows`|Data Type|
|------|---------|
|Star Name|**string**|
|Spectral Type|**string**|
|Stellar Effective Temperature [K]|**float**|
|Stellar Radius [Solar Radius]|**float**|
|Stellar Mass [Solar mass]|**float**|
|Stellar Luminosity [log(Solar)]|**float**|
|Stellar Surface Gravity [log10(cm/s**2)]|**float**|
|Stellar Age [Gyr]|**float**|

**Hint:** You can use the `cell` function defined in P6 and P7 for inspiration here.

Points possible: 2.0

In [42]:
# replace the ... with your code

# the default argument to the parameter 'header' is the global variable 'stars_header' defined above
def star_cell(row_idx, col_name, stars_rows, header=stars_header):
    col_idx = header.index(col_name)
    val = stars_rows[row_idx][col_idx]
    # return None if value is missing
    # else typecast 'val' and return it depending on 'col_name'

    if val in '':
        return None

    if col_name in [
        "Stellar Effective Temperature [K]",
        "Stellar Radius [Solar Radius]",
        "Stellar Mass [Solar mass]",
        "Stellar Luminosity [log(Solar)]",
        "Stellar Surface Gravity [log10(cm/s**2)]",
        "Stellar Age [Gyr]"
    ]:
        return float(val)

    return val

In [43]:
student_grader.check("lab-star_cell", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-star_cell...
Great job! You passed all test cases for this question.


True

#### Lab Question 17: Use the `star_cell` function to find the value of the column `"Spectral Type"` of the **first** star in `"stars_2.csv"`.

Points possible: 2.0

In [44]:
# we have done this one for you

# first read the data in 'stars_2.csv' as a list of lists
stars_2_data = process_csv(os.path.join("small_data", "stars_2.csv"))
stars_2_rows = stars_2_data[1:]

# use the 'star_cell' function to extract the correct value
first_star_type = star_cell(0, 'Spectral Type', stars_2_rows)

first_star_type

'G0'

In [45]:
student_grader.check("lab-q17", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q17...
Great job! You passed all test cases for this question.


True

#### Lab Question 18: Use the `star_cell` function to find the value of the column `"Stellar Age [Gyr]"` of the **second** star in `"stars_2.csv"`.|

Points possible: 2.0

In [46]:
# we have done this one for you
# do not worry if there is no output, the variable is expected to hold the value None

# use the 'star_cell' function to extract the correct value
second_star_age = star_cell(1, 'Stellar Age [Gyr]', stars_2_rows)

second_star_age

In [47]:
student_grader.check("lab-q18", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q18...
Great job! You passed all test cases for this question.


True

#### Lab Question 19: Use the `star_cell` function to find the value of the column `"Stellar Mass [Solar mass]"` of the **third** star in `"stars_2.csv"`.

Points possible: 2.0

In [48]:
# we have done this one for you

# use the 'star_cell' function to extract the correct value
third_star_mass = star_cell(2, 'Stellar Mass [Solar mass]', stars_2_rows)

third_star_mass

1.04

In [49]:
student_grader.check("lab-q19", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q19...
Great job! You passed all test cases for this question.


True

#### Lab Question 20: Create a **dictionary** mapping the `name` of each star in `"stars_2.csv"` to its `Star` object.

You **must** use the `star_cell` function to extract data from `stars_2.csv`.

Your output **must** look like this:
```python
{'HD 158259': Star(spectral_type='G0', stellar_effective_temperature=5801.89, stellar_radius=1.21, 
                   stellar_mass=1.08, stellar_luminosity=0.212, stellar_surface_gravity=4.25, stellar_age=None),
 'K2-187': Star(spectral_type=None, stellar_effective_temperature=5438.0, stellar_radius=0.83, 
                stellar_mass=0.97, stellar_luminosity=-0.21, stellar_surface_gravity=4.6, stellar_age=None),
 'WASP-47': Star(spectral_type=None, stellar_effective_temperature=5552.0, stellar_radius=1.14, 
                 stellar_mass=1.04, stellar_luminosity=0.032, stellar_surface_gravity=4.34, stellar_age=6.5)}
```

Points possible: 2.0

In [50]:
# replace the ... with your code
stars_2_dict = {} # initialize empty dictionary to store all stars

for row_idx in range(len(stars_2_rows)):
    star_name = star_cell(row_idx, 'Star Name', stars_2_rows)
    spectral_type = star_cell(row_idx, 'Spectral Type', stars_2_rows)
    stellar_effective_temperature = float(star_cell(row_idx, 'Stellar Effective Temperature [K]', stars_2_rows))
    # extract the other columns from 'stars_2_rows'
    stellar_radius = float(star_cell(row_idx, 'Stellar Radius [Solar Radius]', stars_2_rows))
    stellar_mass = float(star_cell(row_idx, 'Stellar Mass [Solar mass]', stars_2_rows))
    stellar_luminosity = float(star_cell(row_idx, 'Stellar Luminosity [log(Solar)]', stars_2_rows))
    stellar_surface_gravity = float(star_cell(row_idx, 'Stellar Surface Gravity [log10(cm/s**2)]', stars_2_rows))
    stellar_age = star_cell(row_idx, 'Stellar Age [Gyr]', stars_2_rows)
    
    star = Star(spectral_type, stellar_effective_temperature, stellar_radius, \
                  stellar_mass, stellar_luminosity, \
                  stellar_surface_gravity, stellar_age) # initialize the 'Star' object using the variables defined above
    stars_2_dict[star_name] = star

stars_2_dict

{'HD 158259': Star(spectral_type='G0', stellar_effective_temperature=5801.89, stellar_radius=1.21, stellar_mass=1.08, stellar_luminosity=0.212, stellar_surface_gravity=4.25, stellar_age=None),
 'K2-187': Star(spectral_type=None, stellar_effective_temperature=5438.0, stellar_radius=0.83, stellar_mass=0.97, stellar_luminosity=-0.21, stellar_surface_gravity=4.6, stellar_age=None),
 'WASP-47': Star(spectral_type=None, stellar_effective_temperature=5552.0, stellar_radius=1.14, stellar_mass=1.04, stellar_luminosity=0.032, stellar_surface_gravity=4.34, stellar_age=6.5)}

In [51]:
student_grader.check("lab-q20", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q20...
Great job! You passed all test cases for this question.


True

#### Lab Question 21: Create a **dictionary** mapping the `name` of each star in `"stars_3.csv"` to its `Star` object.

You **must** use the `star_cell` function to extract data from `stars_3.csv`.

Your output **must** look like this:
```python
{'K2-133': Star(spectral_type='M1.5V', stellar_effective_temperature=3655.0, stellar_radius=0.46, 
                stellar_mass=0.46, stellar_luminosity=-1.479, stellar_surface_gravity=4.77, stellar_age=None),
 'K2-138': Star(spectral_type='G8V', stellar_effective_temperature=5356.3, stellar_radius=0.86, 
                stellar_mass=0.94, stellar_luminosity=-0.287, stellar_surface_gravity=4.54, stellar_age=2.8),
 'GJ 667 C': Star(spectral_type='M1.5V', stellar_effective_temperature=3350.0, stellar_radius=None, 
                  stellar_mass=0.33, stellar_luminosity=-1.863, stellar_surface_gravity=4.69, stellar_age=2.0)}
```

Before you can create your `stars_3_dict` variable, you must first read in data from stars_3.csv in the small_data directory using the `process_csv` function.

Points possible: 2.0

In [52]:
# compute and store the answer in the variable 'stars_3_dict', then display it
stars_3_data = process_csv(os.path.join("small_data", "stars_3.csv"))
stars_3_rows = stars_3_data[1:]

stars_3_dict = {}

for row_idx in range(len(stars_3_rows)):
    star_name = star_cell(row_idx, 'Star Name', stars_3_rows)
    spectral_type = star_cell(row_idx, 'Spectral Type', stars_3_rows)
    stellar_effective_temperature = float(star_cell(row_idx, 'Stellar Effective Temperature [K]', stars_3_rows))
    stellar_radius = star_cell(row_idx, 'Stellar Radius [Solar Radius]', stars_3_rows)
    stellar_mass = float(star_cell(row_idx, 'Stellar Mass [Solar mass]', stars_3_rows))
    stellar_luminosity = float(star_cell(row_idx, 'Stellar Luminosity [log(Solar)]', stars_3_rows))
    stellar_surface_gravity = float(star_cell(row_idx, 'Stellar Surface Gravity [log10(cm/s**2)]', stars_3_rows))
    stellar_age = star_cell(row_idx, 'Stellar Age [Gyr]', stars_3_rows)
    
    star = Star(spectral_type, stellar_effective_temperature, stellar_radius, \
                  stellar_mass, stellar_luminosity, \
                  stellar_surface_gravity, stellar_age) 
    stars_3_dict[star_name] = star

stars_3_dict

{'K2-133': Star(spectral_type='M1.5V', stellar_effective_temperature=3655.0, stellar_radius=0.46, stellar_mass=0.46, stellar_luminosity=-1.479, stellar_surface_gravity=4.77, stellar_age=None),
 'K2-138': Star(spectral_type='G8V', stellar_effective_temperature=5356.3, stellar_radius=0.86, stellar_mass=0.94, stellar_luminosity=-0.287, stellar_surface_gravity=4.54, stellar_age=2.8),
 'GJ 667 C': Star(spectral_type='M1.5V', stellar_effective_temperature=3350.0, stellar_radius=None, stellar_mass=0.33, stellar_luminosity=-1.863, stellar_surface_gravity=4.69, stellar_age=2.0)}

In [53]:
student_grader.check("lab-q21", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q21...
Great job! You passed all test cases for this question.


True

#### Lab Question 22: Combine the three **dictionaries** `stars_1_dict`, `stars_2_dict`, and `stars_3_dict` into a single **dictionary** with all the stars in the `small_data` directory.

Points possible: 2.0

In [54]:
# replace the ... with your code

stars_dict = {}

# add stars_1_dict to stars_dict
# stars_dict.update(...)
stars_dict.update(stars_1_dict)
# add stars_2_dict and stars_3_dict to stars_dict
stars_dict.update(stars_2_dict)
stars_dict.update(stars_3_dict)

stars_dict

{'55 Cnc': Star(spectral_type='G8V', stellar_effective_temperature=5172.0, stellar_radius=0.94, stellar_mass=0.91, stellar_luminosity=-0.197, stellar_surface_gravity=4.43, stellar_age=10.2),
 'DMPP-1': Star(spectral_type='F8V', stellar_effective_temperature=6196.0, stellar_radius=1.26, stellar_mass=1.21, stellar_luminosity=0.32, stellar_surface_gravity=4.41, stellar_age=2.01),
 'GJ 876': Star(spectral_type='M2.5V', stellar_effective_temperature=3271.0, stellar_radius=0.3, stellar_mass=0.32, stellar_luminosity=-1.907, stellar_surface_gravity=4.87, stellar_age=1.0),
 'HD 158259': Star(spectral_type='G0', stellar_effective_temperature=5801.89, stellar_radius=1.21, stellar_mass=1.08, stellar_luminosity=0.212, stellar_surface_gravity=4.25, stellar_age=None),
 'K2-187': Star(spectral_type=None, stellar_effective_temperature=5438.0, stellar_radius=0.83, stellar_mass=0.97, stellar_luminosity=-0.21, stellar_surface_gravity=4.6, stellar_age=None),
 'WASP-47': Star(spectral_type=None, stellar_eff

In [55]:
student_grader.check("lab-q22", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q22...
Great job! You passed all test cases for this question.


True

### Data Structure 2: namedtuple `Planet`

Just as you did with the stars, you will be using named tuples to store the data about the planets in the `planets_1.csv`, `planets_2.csv`, and `planets_3.csv` files. Before you start reading these files however, you **must** create a new `Planet` type (using namedtuple). It **must** have the following attributes:

* `planet_name`,
* `host_name`,
* `discovery_method`,
* `discovery_year`,
* `controversial_flag`,
* `orbital_period`,
* `planet_radius`,
* `planet_mass`,
* `semi_major_radius`,
* `eccentricity`,
* `equilibrium_temperature`
* `insolation_flux`.

Points possible: 2.0

In [56]:
# define the namedtuple 'Planet' here
planets_attributes = ['planet_name',
                      'host_name',
                      'discovery_method',
                      'discovery_year',
                      'controversial_flag',
                      'orbital_period',
                      'planet_radius',
                      'planet_mass',
                      'semi_major_radius',
                      'eccentricity',
                      'equilibrium_temperature',
                      'insolation_flux'] # initialize the list of attributes

# define the namedtuple 'Planet'
Planet = namedtuple("Planet", planets_attributes)

In [57]:
student_grader.check("lab-Planet-definition", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-Planet-definition...
Great job! You passed all test cases for this question.


True

#### Create a `Planet` nametuple.

Let us now test whether we have defined the namedtuple properly by creating a `Planet` object.

Points possible: 2.0

In [58]:
# we have done this one for you
jupiter = Planet('Jupiter', 'Sun', 'Imaging', 1610, False, 4333.0, 11.209, 317.828, 5.2038, 0.0489, 110, 0.0345)

jupiter

Planet(planet_name='Jupiter', host_name='Sun', discovery_method='Imaging', discovery_year=1610, controversial_flag=False, orbital_period=4333.0, planet_radius=11.209, planet_mass=317.828, semi_major_radius=5.2038, eccentricity=0.0489, equilibrium_temperature=110, insolation_flux=0.0345)

In [59]:
student_grader.check("lab-Planet-jupiter", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-Planet-jupiter...
Great job! You passed all test cases for this question.


True

### Segment 4.1: Creating `Planet` objects

We are now ready to read the files in the `small_data` directory and create `Planet` objects. Creating `Planet` objects however, is going to be more difficult than creating `Star` objects, because the data required to create a single `Planet` object is split up into different files.

The `planets_1.csv`, `planets_2.csv`, and `planets_3.csv` files contain all the data required to create `Planet` objects **except** for the `host_name`. The `host_name` for each planet is to be found in the `mapping_1.json`, `mapping_2.json`, and `mapping_3.json` files.

First, let us read the data in `planets_1.csv`. Since this is a CSV file, you can use the `process_csv` function from above to read this file. In the cell below, you **must** read the data in `planets_1.csv` and extract the **header** and the non-header **rows** of the file.

#### Lab Question 23: Read the contents of `'planets_1.csv'` into a **list** of **lists** using the `process_csv` function, and extract the **header** and the **rows** in the file.

Points possible: 2.0

In [60]:
# replace the ... with your code

planets_1_csv = process_csv(os.path.join("small_data", "planets_1.csv")) # process_csv(...) # read the data in 'planets_1.csv'
planets_header = planets_1_csv[0]
planets_1_rows = planets_1_csv[1:]

In [61]:
student_grader.check("lab-q23", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q23...
Great job! You passed all test cases for this question.


True

Now, you are ready to read the data in `mapping_1.json`. Since this is a JSON file, you will need a new function to read this file:

In [62]:
# this function uses the 'load' function from the json module (already imported in this notebook) to read files
def read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)

#### Lab Question 24: Read the contents of `'mapping_1.json'` into a **dictionary** using the `read_json` function.

Points possible: 2.0

In [63]:
# we have done this for you

mapping_1_json = read_json(os.path.join("small_data", "mapping_1.json"))

mapping_1_json

{'55 Cnc b': '55 Cnc',
 '55 Cnc c': '55 Cnc',
 'DMPP-1 b': 'DMPP-1',
 'GJ 876 b': 'GJ 876',
 'GJ 876 c': 'GJ 876'}

In [64]:
student_grader.check("lab-q24", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q24...
Great job! You passed all test cases for this question.


True

### Segment 4.2: Combining data from CSV and JSON files

We are now ready to combine the data from `planets_1_rows` and `mapping_1_json` to create `Planet` objects. Before we start, it might be useful to create a function similar to `star_cell` for preprocessing the values in the CSV files.

### Lab Function 2: `planet_cell(row_idx, col_name, planets_rows, header=planets_header)`

Just like the data in `stars_1.csv`, `stars_2.csv`, and `stars_3.csv`, some of the data in `planets_1.csv`, `planets_2.csv`, and `planets_3.csv` is **missing**.  So, now would be a good time to create a function that takes in a `row_idx`, a `col_name` and a **list** of **lists** `planets_rows` (as well as the optional argument `header`) and returns the value of the column `col_name` at the row `row_idx`.

This function **must** typecast the values it returns based on the `col_name`. If the value in `planets_rows` is missing (i.e., it is `''`), then the value returned **must** be `None`.

The **column** of `planets_rows` where the value should be obtained from, and the correct **data type** for the value are listed in the table below:

|Column of `planets_rows`|Data Type|
|------|---------|
|Planet Name|**string**|
|Discovery Year|**int**|
|Discovery Method|**string**|
|Controversial Flag|**bool**|
|Orbital Period [days]|**float**|
|Planet Radius [Earth Radius]|**float**|
|Planet Mass [Earth Mass]|**float**|
|Orbit Semi-Major Axis [au]|**float**|
|Eccentricity|**float**|
|Equilibrium Temperature [K]|**float**|
|Insolation Flux [Earth Flux]|**float**|

**Important Warning:** Notice that the `Controversial Flag` column has to be converted into a **bool**. The data is stored in `planets_1.csv` (and consequently in `planets_rows`) as `"0"/"1"` values (with `"0"` representing `False` and `"1"` representing `True`). However typecasting **strings** to **bools** is not straightforward. Run the following cell and try to figure out what is happening:

In [65]:
strings = ["0", "1", "", " ", "True", "False"]
for string in strings:
    print(bool(string))

True
True
False
True
True
True


If you want to convert the **strings** into **bools**, you will have to explicitly use `if/else` statements to determine whether the value is `"0"` or `"1"`, as can be seen in the starter code below:

Points possible: 2.0

In [66]:
# replace the ... with your code

def planet_cell(row_idx, col_name, planets_rows, header=planets_header):
    col_idx = header.index(col_name) # extract col_idx from col_name and header
    val = planets_rows[row_idx][col_idx] # extract the value at row_idx and col_idx
    if val == '':
        return None
    if col_name in ["Controversial Flag"]:
        if val == "1":
            return True
        else:
            return False
    if col_name in ["Discovery Year"]:
        return int(val)
        
    # for all other columns typecast 'val' and return it depending on col_name
    if col_name in [
        "Orbital Period [days]",
        "Planet Radius [Earth Radius]",
        "Planet Mass [Earth Mass]",
        "Orbit Semi-Major Axis [au]",
        "Eccentricity",
        "Equilibrium Temperature [K]",
        "Insolation Flux [Earth Flux]"
    ]:
        return float(val)

    return val

In [67]:
student_grader.check("lab-planet_cell", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-planet_cell...
Great job! You passed all test cases for this question.


True

#### Lab Question 25: Use the `planet_cell` function to find the value of the column `"Planet Name"` of the **first** planet in `"planets_1.csv"`. 

Points possible: 2.0

In [68]:
# we have done this one for you

first_planet_name = planet_cell(0, 'Planet Name', planets_1_rows)

first_planet_name

'55 Cnc b'

In [69]:
student_grader.check("lab-q25", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q25...
Great job! You passed all test cases for this question.


True

#### Lab Question 26: Use the `planet_cell` function to find the value of the column `"Insolation Flux [Earth Flux]"` of the **first** planet in `"planets_1.csv"`.

Points possible: 2.0

In [70]:
# we have done this one for you
# do not worry if there is no output, the variable is expected to hold the value None

first_planet_flux = planet_cell(0, 'Insolation Flux [Earth Flux]', planets_1_rows)

first_planet_flux

In [71]:
student_grader.check("lab-q26", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q26...
Great job! You passed all test cases for this question.


True

#### Lab Question 27: Use the `planet_cell` function to find the value of the column `"Controversial Flag"` of the **second** planet in `"planets_1.csv"`.

Points possible: 2.0

In [72]:
# compute and store the answer in the variable 'second_planet_controversy', then display it
second_planet_controversy = planet_cell(1, 'Controversial Flag', planets_1_rows)

second_planet_controversy

False

In [73]:
student_grader.check("lab-q27", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q27...
Great job! You passed all test cases for this question.


True

#### Lab Question 28: Create a `Planet` object for the **first** star in `"planets_1.csv"`.

The **attribute** of the `Planet` namedtuple object, the corresponding **column** of the `planets_1.csv` file where the value should be obtained from, and the correct **data type** for the value are listed in the table below:

|Attribute of `Planet` object|Column of `planets_1.csv`|Data Type|
|---------|------|---------|
|`planet_name`|Planet Name|**string**|
|`host_name`| - |**string**|
|`discovery_method`|Discovery Method|**string**|
|`discovery_year`|Discovery Year|**int**|
|`controversial_flag`|Controversial Flag|**bool**|
|`orbital_period`|Orbital Period [days]|**float**|
|`planet_radius`|Planet Radius [Earth Radius]|**float**|
|`planet_mass`|Planet Mass [Earth Mass]|**float**|
|`semi_major_radius`|Orbit Semi-Major Axis [au]|**float**|
|`eccentricity`|Eccentricity|**float**|
|`equilibrium_temperature`|Equilibrium Temperature [K]|**float**|
|`insolation_flux`|Insolation Flux [Earth Flux]|**float**|


The value of the `host_name` attribute is found in `mapping_1.json`.

Points possible: 2.0

In [74]:
# replace the ... with your code

row_idx = 0 # the index of the planet we want to convert into a Planet object

# extract the values from planets_1_rows
planet_name = planet_cell(row_idx, 'Planet Name', planets_1_rows)
host_name = mapping_1_json[planet_name]
discovery_method = planet_cell(row_idx, 'Discovery Method', planets_1_rows)
discovery_year = int(planet_cell(row_idx, 'Discovery Year', planets_1_rows))
controversial_flag = planet_cell(row_idx, 'Controversial Flag', planets_1_rows)
orbital_period = float(planet_cell(row_idx, 'Orbital Period [days]', planets_1_rows))
planet_radius = float(planet_cell(row_idx, 'Planet Radius [Earth Radius]', planets_1_rows))
planet_mass = float(planet_cell(row_idx, 'Planet Mass [Earth Mass]', planets_1_rows))
semi_major_radius = float(planet_cell(row_idx, 'Orbit Semi-Major Axis [au]', planets_1_rows))
eccentricity = float(planet_cell(row_idx, 'Eccentricity', planets_1_rows))
equilibrium_temperature = float(planet_cell(row_idx, 'Equilibrium Temperature [K]', planets_1_rows))
insolation_flux = planet_cell(row_idx, 'Insolation Flux [Earth Flux]', planets_1_rows)

# initialize 'first_planet'
first_planet = Planet(planet_name, host_name, discovery_method, discovery_year,\
                  controversial_flag, orbital_period, planet_radius, planet_mass,\
                  semi_major_radius, eccentricity, equilibrium_temperature, insolation_flux)

first_planet

Planet(planet_name='55 Cnc b', host_name='55 Cnc', discovery_method='Radial Velocity', discovery_year=1996, controversial_flag=False, orbital_period=14.6516, planet_radius=13.9, planet_mass=263.9785, semi_major_radius=0.1134, eccentricity=0.0, equilibrium_temperature=700.0, insolation_flux=None)

In [75]:
student_grader.check("lab-q28", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q28...
Great job! You passed all test cases for this question.


True

#### Lab Question 29: Create a **list** of `Planet` objects of each planet in `"planets_1.csv"`.

Your output **must** look like this:
```python
[Planet(planet_name='55 Cnc b', host_name='55 Cnc', discovery_method='Radial Velocity', 
        discovery_year=1996, controversial_flag=False, orbital_period=14.6516, 
        planet_radius=13.9, planet_mass=263.9785, semi_major_radius=0.1134, eccentricity=0.0,
        equilibrium_temperature=700.0, insolation_flux=None),
 Planet(planet_name='55 Cnc c', host_name='55 Cnc', discovery_method='Radial Velocity', 
        discovery_year=2004, controversial_flag=False, orbital_period=44.3989, 
        planet_radius=8.51, planet_mass=54.4738, semi_major_radius=0.2373, eccentricity=0.03, 
        equilibrium_temperature=None, insolation_flux=None),
 Planet(planet_name='DMPP-1 b', host_name='DMPP-1', discovery_method='Radial Velocity', 
        discovery_year=2019, controversial_flag=False, orbital_period=18.57, 
        planet_radius=5.29, planet_mass=24.27, semi_major_radius=0.1462, eccentricity=0.083, 
        equilibrium_temperature=877.0, insolation_flux=None),
 Planet(planet_name='GJ 876 b', host_name='GJ 876', discovery_method='Radial Velocity', 
        discovery_year=1998, controversial_flag=False, orbital_period=61.1166, 
        planet_radius=13.3, planet_mass=723.2235, semi_major_radius=0.208317, eccentricity=0.0324,
        equilibrium_temperature=None, insolation_flux=None),
 Planet(planet_name='GJ 876 c', host_name='GJ 876', discovery_method='Radial Velocity', 
        discovery_year=2000, controversial_flag=False, orbital_period=30.0881, 
        planet_radius=14.0, planet_mass=226.9846, semi_major_radius=0.12959, eccentricity=0.25591, 
        equilibrium_temperature=None, insolation_flux=None)]
```

Points possible: 2.0

In [76]:
# compute and store the answer in the variable 'planets_1_list', then display it
Planet = namedtuple("Planet", planets_attributes)
planets_1_list = []

for row_idx in range(len(planets_1_rows)):
    planet_name = planet_cell(row_idx, 'Planet Name', planets_1_rows)
    host_name = mapping_1_json[planet_name]
    discovery_method = planet_cell(row_idx, 'Discovery Method', planets_1_rows)
    discovery_year = int(planet_cell(row_idx, 'Discovery Year', planets_1_rows))
    controversial_flag = planet_cell(row_idx, 'Controversial Flag', planets_1_rows)
    orbital_period = float(planet_cell(row_idx, 'Orbital Period [days]', planets_1_rows))
    planet_radius = float(planet_cell(row_idx, 'Planet Radius [Earth Radius]', planets_1_rows))
    planet_mass = float(planet_cell(row_idx, 'Planet Mass [Earth Mass]', planets_1_rows))
    semi_major_radius = float(planet_cell(row_idx, 'Orbit Semi-Major Axis [au]', planets_1_rows))
    eccentricity = float(planet_cell(row_idx, 'Eccentricity', planets_1_rows))
    equilibrium_temperature = planet_cell(row_idx, 'Equilibrium Temperature [K]', planets_1_rows)
    insolation_flux = planet_cell(row_idx, 'Insolation Flux [Earth Flux]', planets_1_rows)
    
    planet = Planet(planet_name, host_name, discovery_method, discovery_year,\
                  controversial_flag, orbital_period, planet_radius, planet_mass,\
                  semi_major_radius, eccentricity, equilibrium_temperature, insolation_flux)
    planets_1_list.append(planet)

planets_1_list

[Planet(planet_name='55 Cnc b', host_name='55 Cnc', discovery_method='Radial Velocity', discovery_year=1996, controversial_flag=False, orbital_period=14.6516, planet_radius=13.9, planet_mass=263.9785, semi_major_radius=0.1134, eccentricity=0.0, equilibrium_temperature=700.0, insolation_flux=None),
 Planet(planet_name='55 Cnc c', host_name='55 Cnc', discovery_method='Radial Velocity', discovery_year=2004, controversial_flag=False, orbital_period=44.3989, planet_radius=8.51, planet_mass=54.4738, semi_major_radius=0.2373, eccentricity=0.03, equilibrium_temperature=None, insolation_flux=None),
 Planet(planet_name='DMPP-1 b', host_name='DMPP-1', discovery_method='Radial Velocity', discovery_year=2019, controversial_flag=False, orbital_period=18.57, planet_radius=5.29, planet_mass=24.27, semi_major_radius=0.1462, eccentricity=0.083, equilibrium_temperature=877.0, insolation_flux=None),
 Planet(planet_name='GJ 876 b', host_name='GJ 876', discovery_method='Radial Velocity', discovery_year=1998

In [77]:
student_grader.check("lab-q29", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q29...
Great job! You passed all test cases for this question.


True

#### Lab Question 30: What is the **fifth** `Planet` object in `'planets_1.csv'`?

You **must** access from the `planets_1_list` to answer this question.

Points possible: 2.0

In [78]:
# compute and store the answer in the variable 'fifth_planet', then display it
fifth_planet = planets_1_list[4]                    

fifth_planet

Planet(planet_name='GJ 876 c', host_name='GJ 876', discovery_method='Radial Velocity', discovery_year=2000, controversial_flag=False, orbital_period=30.0881, planet_radius=14.0, planet_mass=226.9846, semi_major_radius=0.12959, eccentricity=0.25591, equilibrium_temperature=None, insolation_flux=None)

In [79]:
student_grader.check("lab-q30", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q30...
Great job! You passed all test cases for this question.


True

#### Lab Question 31: What is the `planet_name` of the **fifth** `Planet` in `'planets_1.csv'`?

You **must** access from the `planets_1_list` to answer this question. 

Points possible: 2.0

In [80]:
# compute and store the answer in the variable 'fifth_planet_name', then display it
fifth_planet_name = planets_1_list[4].planet_name

fifth_planet_name

'GJ 876 c'

In [81]:
student_grader.check("lab-q31", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q31...
Great job! You passed all test cases for this question.


True

#### Lab Question 32: What is the `controversial_flag` of the **fourth** `Planet` in `'planets_1.csv'`?

You **must** access from the `planets_1_list` to answer this question.

Points possible: 2.0

In [82]:
# compute and store the answer in the variable 'fourth_planet_controversy', then display it
fourth_planet_controversy = planets_1_list[3].controversial_flag

fourth_planet_controversy

False

In [83]:
student_grader.check("lab-q32", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q32...
Great job! You passed all test cases for this question.


True

### Segment 4.3: Data Cleaning - broken CSV rows

The code you have written worked well for reading the data in `planets_1.csv` and `mapping_1.json`. However, it will likely **not** work for `planets_2.csv` and `mapping_2.json`. This is because the file `planets_2.csv` is **broken**. For some reason, a few rows in `planets_2.csv` have their data jumbled up. This is what `planets_2.csv` looks like:

|Planet Name|Discovery Method|Discovery Year|Controversial Flag|Orbital Period [days]|Planet Radius [Earth Radius]|Planet Mass [Earth Mass]|Orbit Semi-Major Axis [au]|Eccentricity|Equilibrium Temperature [K]|Insolation Flux [Earth Flux]|
|-----------|----------------|--------------|------------------|---------------------|----------------------------|------------------------|--------------------------|------------|---------------------------|----------------------------|
|HD 158259 b|Radial Velocity|2020|0|2.17800000|1.292|2.22000|||1478|794.22|
|K2-187 b|Transit|2018|0|0.77401000|1.200|1.87000|0.016400||1815||
|K2-187 c|Transit|2018|0|2.87151200|1.400|2.54000|0.039200||1173||
|K2-187 d|K2-187|Transit|2018|0|7.14958400|2.400|6.35000|0.072000||865|
|WASP-47 b|2012|Transit|0|4.15914920|12.640|363.60000|0.052000|0.002800|1275|534.00|

We can see that for some reason, in the **fourth** row, the value under the column `Discovery Method` is the name of the planet's host star. This is causing all the other columns in the row to also take meaningless values.

Similarly, in the **fifth** row, we see that the values under the columns `Discovery Method` and `Discovery Year` are swapped.

We will call such a **row** in a CSV file where the values under a column do not match the expected format to be a **broken row**. While it is possible to sometimes extract useful data from broken rows, in this lab and in P10, we will simply **skip** broken rows.

In order to **skip** broken rows, you should first know how to recognize a **broken row**. In general, there is no general rule that helps you identify when a row is broken. This is because CSV rows can be **broken** in all sorts of different ways. Thankfully, we don't have to write code to catch all sorts of weird cases. It will suffice for us to manually **inspect** the file `planets_2.csv`, and identify **how** the rows are broken.

The simplest way to recognize if a row is broken is if you run into any **RunTime Errors** when you execute your code. So, one simple way to skip bad rows would be to use `try/except` blocks to avoid processing any rows that cause the code to crash.

**Important Note:** In this dataset, as you might have already noticed, it would be **significantly harder** to detect **broken rows** where some of the numerical values are swapped (for example, `Planet Radius [Earth Radius]` and `Planet Mass [Earth Mass]`). You may **assume** that the numerical values are **not** swapped in **any** row, and that **only the rows** in which the **data types** are not as expected are **broken**.

#### Lab Question 33: Create a **list** of `Planet` objects of each planet in `"planets_2.csv"`.

You **must** skip any broken rows in the CSV file. Your output **must** look like this:
```python
[Planet(planet_name='HD 158259 b', host_name='HD 158259', discovery_method='Radial Velocity', 
        discovery_year=2020, controversial_flag=False, orbital_period=2.178, 
        planet_radius=1.292, planet_mass=2.22, semi_major_radius=None, eccentricity=None, 
        equilibrium_temperature=1478.0, insolation_flux=794.22),
 Planet(planet_name='K2-187 b', host_name='K2-187', discovery_method='Transit', 
        discovery_year=2018, controversial_flag=False, orbital_period=0.77401, 
        planet_radius=1.2, planet_mass=1.87, semi_major_radius=0.0164, eccentricity=None, 
        equilibrium_temperature=1815.0, insolation_flux=None),
 Planet(planet_name='K2-187 c', host_name='K2-187', discovery_method='Transit', 
        discovery_year=2018, controversial_flag=False, orbital_period=2.871512, 
        planet_radius=1.4, planet_mass=2.54, semi_major_radius=0.0392, eccentricity=None, 
        equilibrium_temperature=1173.0, insolation_flux=None)]
```

Points possible: 2.0

In [84]:
# replace the ... with your code
planets_2_data = process_csv(os.path.join("small_data", "planets_2.csv")) # read planets_2.csv
planets_2_rows = planets_2_data[1:] # extract the rows from planets_2_data
mapping_2_json = read_json(os.path.join("small_data", "mapping_2.json")) # read mapping_2.json
Planet = namedtuple("Planet", planets_attributes)

#         pass # replace with your code
#         # create a Planet object and append to 'planets_2_list'
planets_2_list = []
for row_idx in range(len(planets_2_rows)): # for row_idx in range(len(planets_2_rows)):
    try: # try:
        planet_name = planet_cell(row_idx, 'Planet Name', planets_2_rows)
        host_name = mapping_2_json[planet_name]
        discovery_method = planet_cell(row_idx, 'Discovery Method', planets_2_rows)
        discovery_year = int(planet_cell(row_idx, 'Discovery Year', planets_2_rows))
        controversial_flag = planet_cell(row_idx, 'Controversial Flag', planets_2_rows)
        orbital_period = float(planet_cell(row_idx, 'Orbital Period [days]', planets_2_rows))
        planet_radius = float(planet_cell(row_idx, 'Planet Radius [Earth Radius]', planets_2_rows))
        planet_mass = float(planet_cell(row_idx, 'Planet Mass [Earth Mass]', planets_2_rows))
        semi_major_radius = planet_cell(row_idx, 'Orbit Semi-Major Axis [au]', planets_2_rows)
        eccentricity = planet_cell(row_idx, 'Eccentricity', planets_2_rows)
        equilibrium_temperature = planet_cell(row_idx, 'Equilibrium Temperature [K]', planets_2_rows)
        insolation_flux = planet_cell(row_idx, 'Insolation Flux [Earth Flux]', planets_2_rows)
        
        planet = Planet(planet_name, host_name, discovery_method, discovery_year,\
                  controversial_flag, orbital_period, planet_radius, planet_mass,\
                  semi_major_radius, eccentricity, equilibrium_temperature, insolation_flux)
        planets_2_list.append(planet)
    except ValueError: #     except ValueError:
        continue #         continue

planets_2_list

[Planet(planet_name='HD 158259 b', host_name='HD 158259', discovery_method='Radial Velocity', discovery_year=2020, controversial_flag=False, orbital_period=2.178, planet_radius=1.292, planet_mass=2.22, semi_major_radius=None, eccentricity=None, equilibrium_temperature=1478.0, insolation_flux=794.22),
 Planet(planet_name='K2-187 b', host_name='K2-187', discovery_method='Transit', discovery_year=2018, controversial_flag=False, orbital_period=0.77401, planet_radius=1.2, planet_mass=1.87, semi_major_radius=0.0164, eccentricity=None, equilibrium_temperature=1815.0, insolation_flux=None),
 Planet(planet_name='K2-187 c', host_name='K2-187', discovery_method='Transit', discovery_year=2018, controversial_flag=False, orbital_period=2.871512, planet_radius=1.4, planet_mass=2.54, semi_major_radius=0.0392, eccentricity=None, equilibrium_temperature=1173.0, insolation_flux=None)]

In [85]:
student_grader.check("lab-q33", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q33...
Great job! You passed all test cases for this question.


True

**Important Warning:** It is considered a bad coding practice to use *bare* `try/except` blocks. This means that you should **never** write code like this:

```python
try:
    # some code
except:
    # some other code
```

If you use *bare* `try/except` blocks, your code will seemingly work even if there are bugs in there, and it can get very hard to debug. You should always **explicitly** catch for specific errors like this:

```python
try:
    # some code
except ValueError:
    # some other code
except IndexError:
    # some other code
```

This way, your code will still crash if there is some other unexpected bug in your code that needs to be fixed, and will only go to the `except` block if it runs into a `ValueError` or an `IndexError`. The starter code above already catches specifically for `ValueError`. You **must** continue this practice in P10 as well.

### Segment 4.4: Data Cleaning - broken JSON files

So far, we have written code that can read `planets_1.csv` and `mapping_1.json`, as well as `planets_2.csv` and `mapping_2.json`. However, if you try to read `mapping_3.json`, you are likely to run into some issues. This is because the file `mapping_3.json` is **broken**. Unlike **broken** CSV files, where we only had to skip the **broken rows**, it is much harder to parse **broken JSON files**. When a JSON file is **broken**, we often have no choice but to **skip the file entirely**.

It is also not easy to detect if a JSON file is **broken** using `if` statements. The easiest is to simply try to read the file using the `read_json` function and check if the code crashes.

#### Lab Question 34: Determine if the `'mapping_3.json'` file is **broken** using a `try/except` block.

Points possible: 3.0

In [86]:
# we have done this one for you

try:
    mapping_3_json = read_json(os.path.join("small_data", "mapping_3.json"))
except json.JSONDecodeError:
    mapping_3_json = {}
    
mapping_3_json

{}

In [87]:
student_grader.check("lab-q34", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q34...
Great job! You passed all test cases for this question.


True

In the above cell, note that in the `try/except` block, we specifically checked for the `json.JSONDecodeError`. This is the error that is thrown when you try to call `json.load` on a **broken** JSON file.

### Segment 5: Data Analysis

We have now managed to read all the data in the `small_data` directory. Now is the time to test if our data structures work!

#### Lab Question 35: What is the `host_name` of the **second** planet in `'planets_2.csv'`?

You **must** skip any broken rows. So, you can directly access from the list `planets_2_list` to answer this question.

Points possible: 2.0

In [88]:
# compute and store the answer in the variable 'second_planet_host', then display it
second_planet_host = planets_2_list[1].host_name

second_planet_host

'K2-187'

In [89]:
student_grader.check("lab-q35", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q35...
Great job! You passed all test cases for this question.


True

#### Lab Question 36: What is the `Star` object of the **third** planet in `'planets_2.csv'`?

You **must** skip any broken rows. So, you can directly access from the list `planets_2_list` to answer this question.

Note that a planet's star can be looked up using the planet's host name attribute.

**Hint:** You can use the `stars_dict` **dictionary** defined in q12.2 to find the `Star` object given a star's name.

Points possible: 2.0

In [90]:
# compute and store the answer in the variable 'third_planet_star', then display it
third_planet_host = planets_2_list[2].host_name
third_planet_star = stars_dict.get(third_planet_host, None)

third_planet_star

Star(spectral_type=None, stellar_effective_temperature=5438.0, stellar_radius=0.83, stellar_mass=0.97, stellar_luminosity=-0.21, stellar_surface_gravity=4.6, stellar_age=None)

In [91]:
student_grader.check("lab-q36", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q36...
Great job! You passed all test cases for this question.


True

#### Lab Question 37: What is the `stellar_radius` of the star around which the **first** planet in `'planets_1.csv'` orbits?

You can directly access from the list `planets_1_list` to answer this question.

Points possible: 2.0

In [92]:
# compute and store the answer in the variable 'first_planet_star_radius', then display it
first_planet_host = planets_1_list[0].host_name
first_planet_star = stars_dict.get(first_planet_host, None)

first_planet_star_radius = first_planet_star.stellar_radius if first_planet_star else None

first_planet_star_radius

0.94

In [93]:
student_grader.check("lab-q37", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for lab-q37...
Great job! You passed all test cases for this question.


True

### Submit the lab

Great work! You are now ready to submit lab-p10.
 **Submit your p10.ipynb on Gradescope to the lab-p10 assignment**, like usual. Remember that the grades for the lab portion of the project and the actual assignment grade are independent. You will submit the same notebook (at different levels of completion) to two different assignments.

## Project Portion (20 Questions)

### Setup:

Before proceeding much further, you need to make sure that the project files are stored in the following structure:

```
+-- p10.ipynb
+-- (other files)
+-- data
|   +-- mapping_1.json
|   +-- mapping_2.json
|   +-- mapping_3.json
|   +-- mapping_4.json
|   +-- mapping_5.json
|   +-- planets_1.csv
|   +-- planets_2.csv
|   +-- planets_3.csv
|   +-- planets_4.csv
|   +-- planets_5.csv
|   +-- stars_1.csv
|   +-- stars_2.csv
|   +-- stars_3.csv
|   +-- stars_4.csv
|   +-- stars_5.csv
```

Make sure that the files are inside the `data` directory. If you place your files inside some other directory, then your code will **fail on Gradescope** even after passing local tests.

### Project Description:

Cleaning data is an important part of a data scientist's work cycle. As you have already seen, the data we will be analyzing in P10 and P11 has been split up into 15 different files of different formats. Even worse, as you shall see later in this project, some of these files have been corrupted, and lots of data is missing. Unfortunately, in the real world, a lot of data that you will come across will be in rough shape, and it is your job to clean it up before you can analyze it. In P10, you will combine the data in these different files to create a few manageable data structures, which can be easily analyzed. In the process, you will also have to deal with broken CSV files (by skipping rows with broken data), and broken JSON files (by skipping the files entirely).

After you create these data structures, in P11, you will dive deeper by analyzing this data and arrive at some exciting conclusions about various planets and stars outside our Solar System.

### Project Requirements:

You **may not** hardcode indices in your code, unless the question explicitly says to. If you open your `.csv` files with Excel, manually count through the rows and use this number to loop through the dataset, this is also considered as hardcoding.

**Store** your final answer for each question in the **variable specified for each question**.

For some of the questions, we'll ask you to write (then use) a function to compute the answer. If you compute the answer **without** creating the function we ask you to write, the grader autograder will **not** award points, even if you produced the right answer.

#### Required Functions:
- `star_cell`
- `get_stars`
- `planet_cell`
- `get_planets`

In this project, you will also be required to define certain **data structures**. If you do not create these data structures exactly as specified, the Gradescope autograder will **deduct** points from your public score, even if the way you did it produced the correct answer.

#### Required Data Structures:
- `Star` (**namedtuple**)
- `stars_dict` (**dictionary** mapping **strings** to `Star` objects)
- `Planet` (**namedtuple**)
- `planets_list` (**list** of `Planet` objects)

In addition, you are also **required** to follow the requirements below:

* You **must** never use the output of the `os.listdir` function directly. You **must** always first remove all files and directories that start with `"."`, and **explicitly sort** the list before doing anything with it.
* You are **not** allowed to use **bare** `try/except` blocks. In other words, you can **not** use `try/except` without explicitly specifying the type of exceptions that you want to catch.
* You are **only** allowed to use Python commands and concepts that have been taught in the course prior to the release of P10. In particular, this means that you are **not** allowed to use **modules** like `pandas` to answer the questions in this project.
* Please do not display `stars_dict` or `planets_list` anywhere in the notebook. Please **remove** such statements before submission.

Otherwise, the Gradescope autograder may **deduct** points from your score.

### File handling:

In the next questions, you will be using functions in the `os` module to make **lists** of files and paths in the `data` directory. All your **lists** **must** satisfy the following conditions:

* Any files with names beginning with `"."` **must** be **excluded**.
* The list **must** be **explicitly sorted** in **reverse-alphabetical** order after **splitting** by the **path separator**.

#### Question 1: What are the **names** of the files present in the `data` directory?

Your output **must** be a **list** of **strings** representing the **names** of the files sorted in reverse-alphabetical order.

Points possible: 3.0

In [94]:
# compute and store the answer in the variable 'files_in_data', then display it
import os
all_files = os.listdir('data')
actual_files = [file for file in all_files if not file.startswith('.')]
files_in_data = sorted(actual_files, reverse = True)

files_in_data

['stars_5.csv',
 'stars_4.csv',
 'stars_3.csv',
 'stars_2.csv',
 'stars_1.csv',
 'planets_5.csv',
 'planets_4.csv',
 'planets_3.csv',
 'planets_2.csv',
 'planets_1.csv',
 'mapping_5.json',
 'mapping_4.json',
 'mapping_3.json',
 'mapping_2.json',
 'mapping_1.json']

In [95]:
student_grader.check("q1", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q1...
Great job! You passed all test cases for this question.


True

#### Question 2: What are the **paths** of all the files in the `data` directory?

Your output **must** be a **list** of **strings** representing the **paths** of the files. You **must** use the `files_in_data` variable created in the previous question to answer this.

**Warning:** Please **do not hardcode** `"/"` or `"\"` in your path because doing so will cause your function to **fail** on a computer that's not using the same operating system as yours. This may result in your code failing on Gradescope. 

Points possible: 3.0

In [96]:
# compute and store the answer in the variable 'file_paths', then display it
import os
all_files = os.listdir('data')
actual_files = [file for file in all_files if not file.startswith('.')]
files_in_data = sorted(actual_files, reverse = True)

file_paths = [os.path.join("data", file) for file in files_in_data]

file_paths

['data/stars_5.csv',
 'data/stars_4.csv',
 'data/stars_3.csv',
 'data/stars_2.csv',
 'data/stars_1.csv',
 'data/planets_5.csv',
 'data/planets_4.csv',
 'data/planets_3.csv',
 'data/planets_2.csv',
 'data/planets_1.csv',
 'data/mapping_5.json',
 'data/mapping_4.json',
 'data/mapping_3.json',
 'data/mapping_2.json',
 'data/mapping_1.json']

In [97]:
student_grader.check("q2", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q2...
Great job! You passed all test cases for this question.


True

#### Question 3: What are the **paths** of all the **CSV files** present in `data` directory?

Your output **must** be filtered to **only** include files ending in `'.csv'`. You **must** use either the `files_in_data` or `file_paths` variables created in the previous questions to answer this.

**Warning:** Please **do not hardcode** `"/"` or `"\"` in your path because doing so will cause your function to **fail** on a computer that's not using the same operating system as yours. This may result in your code failing on Gradescope.

Points possible: 3.0

In [98]:
# compute and store the answer in the variable 'csv_file_paths', then display it
import os
all_files = os.listdir('data')
actual_files = [file for file in all_files if not file.startswith('.')]
files_in_data = sorted(actual_files, reverse = True)
file_paths = [os.path.join("data", file) for file in files_in_data]
paths_in_files_in_data = sorted(file_paths, key = lambda path: path.split(os.path.sep), reverse=True)

csv_file_paths = [path for path in file_paths if path.endswith(".csv")]

csv_file_paths

['data/stars_5.csv',
 'data/stars_4.csv',
 'data/stars_3.csv',
 'data/stars_2.csv',
 'data/stars_1.csv',
 'data/planets_5.csv',
 'data/planets_4.csv',
 'data/planets_3.csv',
 'data/planets_2.csv',
 'data/planets_1.csv']

In [99]:
student_grader.check("q3", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q3...
Great job! You passed all test cases for this question.


True

#### Question 4: What are the **paths** of all the files present in `data` directory, that **begin** with the phrase `'stars'`?

Your output **must** be filtered to **only** include files start with `'stars'`. You **must** use either the `files_in_data` or `file_paths` variables created in the previous questions to answer this.

**Warning:** Please **do not hardcode** `"/"` or `"\"` in your path because doing so will cause your function to **fail** on a computer that's not using the same operating system as yours. This may result in your code failing on Gradescope.

Points possible: 3.0

In [161]:
# compute and store the answer in the variable 'stars_paths', then display it
stars_paths = [path for path in file_paths if os.path.basename(path).startswith("star")]

stars_paths

['data/stars_5.csv',
 'data/stars_4.csv',
 'data/stars_3.csv',
 'data/stars_2.csv',
 'data/stars_1.csv']

In [162]:
student_grader.check("q4", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q4...
Great job! You passed all test cases for this question.


True

#### Read in `stars_1.csv` data

Points possible: 3.0

In [102]:
# replace the ... with your code

stars_1_csv = process_csv(os.path.join("data", "stars_1.csv")) # read the data in 'stars_1.csv'
stars_header = stars_1_csv[0]
stars_1_rows = stars_1_csv[1:]

In [103]:
student_grader.check("Read-in-stars1", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for Read-in-stars1...
Great job! You passed all test cases for this question.


True

#### Question 5: Create a `Star` object for the **third** star (i.e., *row index* **2**) in `"stars_1.csv"`.

You **must** access the values in `stars_1.csv` using the `star_cell` function. Note that the third star would be at **index** 2.

The **attribute** of the `Star` namedtuple object, the corresponding **column** of the `stars_1.csv` file where the value should be obtained from, and the correct **data type** for the value are listed in the table below:

|Attribute of `Star` object|Column of `stars_1.csv`|Data Type|
|---------|------|---------|
|`spectral_type`|Spectral Type|**string**|
|`stellar_effective_temperature`|Stellar Effective Temperature [K]|**float**|
|`stellar_radius`|Stellar Radius [Solar Radius]|**float**|
|`stellar_mass`|Stellar Mass [Solar mass]|**float**|
|`stellar_luminosity`|Stellar Luminosity [log(Solar)]|**float**|
|`stellar_surface_gravity`|Stellar Surface Gravity [log10(cm/s**2)]|**float**|
|`stellar_age`|Stellar Age [Gyr]|**float**|

Points possible: 3.0

In [104]:
 # compute and store the answer in the variable 'third_star', then display it
Star = namedtuple("Star", ["spectral_type", "stellar_effective_temperature", "stellar_radius", "stellar_mass", "stellar_luminosity", "stellar_surface_gravity", "stellar_age"])
spectral_type = star_cell(2, "Spectral Type", stars_1_rows)
stellar_effective_temperature = float(star_cell(2, "Stellar Effective Temperature [K]", stars_1_rows))
stellar_radius = float(star_cell(2, "Stellar Radius [Solar Radius]", stars_1_rows))
stellar_mass = float(star_cell(2, "Stellar Mass [Solar mass]", stars_1_rows))
stellar_luminosity = float(star_cell(2, "Stellar Luminosity [log(Solar)]", stars_1_rows))
stellar_surface_gravity = float(star_cell(2, "Stellar Surface Gravity [log10(cm/s**2)]", stars_1_rows))
stellar_age = float(star_cell(2, "Stellar Age [Gyr]", stars_1_rows))

third_star = Star(spectral_type, stellar_effective_temperature, stellar_radius, stellar_mass, stellar_luminosity, stellar_surface_gravity, stellar_age)

third_star

Star(spectral_type='K0III', stellar_effective_temperature=4888.0, stellar_radius=11.55, stellar_mass=1.78, stellar_luminosity=1.84, stellar_surface_gravity=2.55, stellar_age=4.5)

In [105]:
student_grader.check("q5", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q5...
Great job! You passed all test cases for this question.


True

### Project Function 1:  `get_stars(star_file)`

This function **must** take in as its input, the path of a CSV file `star_file` which contains data on stars in the same format as `stars_1.csv`. It **must** return a **dictionary** mapping the `Name` of each star in `star_file` to a `Star` object containing all the other details of the star.

You **must** access the values in `star_file` using the `star_cell` function.

You **must not** hardcode the name of the directory `data` into the `get_stars` function. Instead, you must pass it as a part of the argument `star_file`, by including it in the **path** `star_file`. In other words, if you want to read the contents of the file `stars_5.csv`, your function call must **not** be: `get_stars("stars_5.csv")`. Instead, it must be:

```python
get_stars(os.path.join("data", "stars_5.csv"))
```

For example, when this function is called with the **path** to the file `stars_1.csv` as the input, the **dictionary** returned should look like:

```python
{'11 Com': Star(spectral_type='G8III', stellar_effective_temperature=4874.0, 
                stellar_radius=13.76, stellar_mass=2.09, stellar_luminosity=1.978, 
                stellar_surface_gravity=2.45, stellar_age=None),
 '11 UMi': Star(spectral_type='K4III', stellar_effective_temperature=4213.0, 
                tellar_radius=29.79, stellar_mass=2.78, stellar_luminosity=2.43, 
                stellar_surface_gravity=1.93, stellar_age=1.56),
 '14 And': Star(spectral_type='K0III', stellar_effective_temperature=4888.0, 
                stellar_radius=11.55, stellar_mass=1.78, stellar_luminosity=1.84, 
                stellar_surface_gravity=2.55, stellar_age=4.5),
 ...
}
```

Points possible: 3.0

In [106]:
# define the function 'get_stars' here

def get_stars(star_file):
    stars_csv = process_csv(star_file) 
    stars_header = stars_csv[0]
    stars_rows = stars_csv[1:]

    stars_dict = {}

    for idx in range(len(stars_rows)):
        star_name = star_cell(idx, "Star Name", stars_rows)
        spectral_type = star_cell(idx, "Spectral Type", stars_rows)
        stellar_effective_temperature = star_cell(idx, "Stellar Effective Temperature [K]", stars_rows)
        stellar_radius = star_cell(idx, "Stellar Radius [Solar Radius]", stars_rows)
        stellar_mass = star_cell(idx, "Stellar Mass [Solar mass]", stars_rows)
        stellar_luminosity = star_cell(idx, "Stellar Luminosity [log(Solar)]", stars_rows)
        stellar_surface_gravity = star_cell(idx, "Stellar Surface Gravity [log10(cm/s**2)]", stars_rows)
        stellar_age = star_cell(idx, "Stellar Age [Gyr]", stars_rows)
        
        star = Star(
            spectral_type, stellar_effective_temperature, stellar_radius,
            stellar_mass, stellar_luminosity, stellar_surface_gravity, stellar_age
        )
        
        stars_dict[star_name] = star
    
    return stars_dict

In [107]:
student_grader.check("get_stars", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for get_stars...
Great job! You passed all test cases for this question.


True

#### Define `stars_1_dict` using the get_stars fuction

Points possible: 3.0

In [108]:
# you can now use 'get_stars' to read the data in 'stars_1.csv'

stars_1_dict = get_stars(os.path.join("data", "stars_1.csv"))

stars_1_dict

{'11 Com': Star(spectral_type='G8III', stellar_effective_temperature=4874.0, stellar_radius=13.76, stellar_mass=2.09, stellar_luminosity=1.978, stellar_surface_gravity=2.45, stellar_age=None),
 '11 UMi': Star(spectral_type='K4III', stellar_effective_temperature=4213.0, stellar_radius=29.79, stellar_mass=2.78, stellar_luminosity=2.43, stellar_surface_gravity=1.93, stellar_age=1.56),
 '14 And': Star(spectral_type='K0III', stellar_effective_temperature=4888.0, stellar_radius=11.55, stellar_mass=1.78, stellar_luminosity=1.84, stellar_surface_gravity=2.55, stellar_age=4.5),
 '16 Cyg B': Star(spectral_type='G3V', stellar_effective_temperature=5750.0, stellar_radius=1.13, stellar_mass=1.08, stellar_luminosity=0.097, stellar_surface_gravity=4.36, stellar_age=7.4),
 '17 Sco': Star(spectral_type='K3III', stellar_effective_temperature=4157.0, stellar_radius=25.92, stellar_mass=1.22, stellar_luminosity=2.254, stellar_surface_gravity=1.7, stellar_age=5.13),
 '18 Del': Star(spectral_type='G6III', st

In [109]:
student_grader.check("stars_1_dict", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for stars_1_dict...
Great job! You passed all test cases for this question.


True

#### Question 6: What is the `Star` object of the star (in `stars_1.csv`) named *DP Leo*?

You **must** access the `Star` object in `stars_1_dict` **dictionary** defined above to answer this question.

Points possible: 3.0

In [110]:
# compute and store the answer in the variable 'dp_leo', then display it
dp_leo = stars_1_dict["DP Leo"]

dp_leo

Star(spectral_type=None, stellar_effective_temperature=13500.0, stellar_radius=0.01, stellar_mass=0.69, stellar_luminosity=-2.4, stellar_surface_gravity=None, stellar_age=None)

In [111]:
student_grader.check("q6", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q6...
Great job! You passed all test cases for this question.


True

#### Question 7: What's the **average** `stellar_luminosity` of **all** the stars in the `star_1.csv` file?

You **must** use the `stars_1_dict` **dictionary** defined above to answer this question.

To find the average, you **must** first **add** up the `stellar_luminosity` value of all the stars and **divide** by the total **number** of stars. You **must skip** stars which don't have the `stellar_luminosity` data. Such stars should not contribute to either the sum of `stellar_luminosity` or to the number of stars. 

Points possible: 3.0

In [177]:
# compute and store the answer in the variable 'avg_lum_stars_1', then display it
star_count = len(stars_1_dict)
total_stellar_luminosity = 0

for star in stars_1_dict:
    star_stellar_luminosity = stars_1_dict[star].stellar_luminosity
    if star_stellar_luminosity == None:
        star_count -= 1
    else:
        total_stellar_luminosity += star_stellar_luminosity

avg_lum_stars_1 = total_stellar_luminosity / star_count

avg_lum_stars_1

0.017454783748361704

In [178]:
student_grader.check("q7", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q7...
Great job! You passed all test cases for this question.


True

#### Question 8: What is the **average** `stellar_age` of **all** the stars in the `stars_2.csv` file?

You **must** use the function `get_stars(csv_file)` to read the data in `stars_2.csv`. Your output **must** be a **float** representing the `stellar_age` in units of *gigayears*. You **must** skip stars which have missing `stellar_age` data. 

Points possible: 3.0

In [179]:
# compute and store the answer in the variable 'avg_age_stars_2', then display it
stars_2_file = os.path.join("data", "stars_2.csv")
stars_2_dict = get_stars(stars_2_file)
star_2_count = len(stars_2_dict)

total_stellar_age = 0
for star in stars_2_dict:
    star_stellar_age = stars_2_dict[star].stellar_age
    if star_stellar_age == None:
        star_2_count -= 1
    else:
        total_stellar_age += star_stellar_age

if star_2_count > 0:
    avg_age_stars_2 = total_stellar_age / star_2_count
else:
    avg_age_stars_2 = None

avg_age_stars_2

4.333537808641972

In [180]:
student_grader.check("q8", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q8...
Great job! You passed all test cases for this question.


True

### Project Data Structure 1: `stars_dict`

You are now ready to read all the data about the stars stored in the `data` directory. You **must** now create a **dictionary** mapping the `Name` of each star in the `data` directory (inside the files `stars_1.csv`, ..., `stars_5.csv`) to the `Star` object containing all the other details about the star.

You **must not** hardcode the files/paths of the files `stars_1.csv`, ..., `stars_5.csv` to answer this question. Instead, you **must** use the `stars_paths` variable defined earlier in Question 4 to get the list of paths needed for this question. You can use the `update` dictionary **method** to combine two **dictionaries**.

You must use this dictionary to answer the next 3 questions.

Points possible: 3.0

In [116]:
# define the variable 'stars_dict' here,
# but do NOT display the variable at the end
stars_dict = {}

for path in stars_paths:
    combined_d = get_stars(path)
    stars_dict.update(combined_d)

In [117]:
student_grader.check("stars_dict_full", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for stars_dict_full...
Great job! You passed all test cases for this question.


True

#### Question 9: What is the `stellar_effective_temperature` of the star *Kepler-220*?

You **must** access the correct `Star` object in the `stars_dict` **dictionary** defined above to answer this question.

Points possible: 4.0

In [118]:
# compute and store the answer in the variable 'kepler_220_temp', then display it
kepler_220_temp = stars_dict["Kepler-220"].stellar_effective_temperature

kepler_220_temp

4632.0

In [119]:
student_grader.check("q9", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q9...
Great job! You passed all test cases for this question.


True

#### Question 10: Find the **name** of the **largest** star (in terms of `stellar_radius`) in the `data` directory.

Your output **must** be a **string**. You do **not** need to worry about any ties. You **must** skip any stars with **missing** `stellar_radius` data.

Points possible: 4.0

In [181]:
# compute and store the answer in the variable 'biggest_star', then display it
biggest_star = None
biggest_star_stellar_radius = 0

for star in stars_dict:
    star_stellar_radius = stars_dict[star].stellar_radius
    if star_stellar_radius == None:
        continue
    elif star_stellar_radius == None or star_stellar_radius > biggest_star_stellar_radius:
        biggest_star = star
        biggest_star_stellar_radius = star_stellar_radius

biggest_star

'HD 18438'

In [182]:
student_grader.check("q10", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q10...
Great job! You passed all test cases for this question.


True

#### Question 11: What is the **average** `stellar_age` (in gigayears) of **all** the stars in the `data` directory whose names **start with** `"Kepler"`?

Your output **must** be a **float**. You **must** skip all stars with **missing** `stellar_age` data. Such stars should not contribute to either the sum of `stellar_age` or to the number of stars.

Points possible: 4.0

In [122]:
# compute and store the answer in the variable 'avg_age_kepler', then display it
total_kepler_age = 0
kepler_count = 0

for star in stars_dict:
    if star.startswith("Kepler"):
        if stars_dict[star].stellar_age == None:
            continue
        else:
            total_kepler_age += stars_dict[star].stellar_age
            kepler_count += 1

avg_age_kepler = total_kepler_age / kepler_count

avg_age_kepler

4.2413036196650715

In [123]:
student_grader.check("q11", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q11...
Great job! You passed all test cases for this question.


True

### Creating `Planet` objects

We are now ready to read the files in the `data` directory and create `Planet` objects. Creating `Planet` objects however, is going to be more difficult than creating `Star` objects, because the data required to create a single `Planet` object is split up into different files.

The `planets_1.csv`, ..., `planets_5.csv` files contain all the data required to create `Planet` objects **except** for the `host_name`. The `host_name` for each planet is to be found in the `mapping_1.json`, ..., `mapping_5.json` files.

First, let us read the data in `planets_1.csv`. Since this is a CSV file, you can use the `process_csv` function from above to read this file. In the cell below, you **must** read the data in `planets_1.csv` and extract the **header** and the non-header **rows** of the file.

#### Read in `planets_1.csv` data

Points possible: 4.0

In [124]:
# replace the ... with your code

planets_1_csv = process_csv(os.path.join("data", "planets_1.csv")) # process_csv(...) # read the data in 'planets_1.csv'
planets_header = planets_1_csv[0]
planets_1_rows = planets_1_csv[1:]

In [125]:
student_grader.check("Read-in-planets1", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for Read-in-planets1...
Great job! You passed all test cases for this question.


True

#### Read in `mapping_1.json` with the read_json function.

Points possible: 4.0

In [126]:
# now use the read_json function to read 'mapping_1.json' into the variable mapping_1_json
def read_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)
        
mapping_1_json = read_json(os.path.join("data", "mapping_1.json"))

mapping_1_json

{'11 Com b': '11 Com',
 '11 UMi b': '11 UMi',
 '14 And b': '14 And',
 '16 Cyg B b': '16 Cyg B',
 '17 Sco b': '17 Sco',
 '18 Del b': '18 Del',
 '1RXS J160929.1-210524 b': '1RXS J160929.1-210524',
 '24 Boo b': '24 Boo',
 '2M0437 b': '2MASS J04372171+2651014',
 '2MASS J01033563-5515561 AB b': '2MASS J01033563-5515561 A',
 '2MASS J01225093-2439505 b': '2MASS J01225093-2439505',
 '2MASS J02192210-3925225 b': '2MASS J02192210-3925225',
 '2MASS J04414489+2301513 b': '2MASS J04414489+2301513',
 '2MASS J12073346-3932539 b': '2MASS J12073346-3932539',
 '2MASS J22362452+4751425 b': '2MASS J22362452+4751425',
 '30 Ari B b': '30 Ari B',
 '4 UMa b': '4 UMa',
 '42 Dra b': '42 Dra',
 '51 Eri b': '51 Eri',
 '51 Peg b': '51 Peg',
 '6 Lyn b': '6 Lyn',
 '70 Vir b': '70 Vir',
 '8 UMi b': '8 UMi',
 '81 Cet b': '81 Cet',
 '91 Aqr b': '91 Aqr',
 'AB Aur b': 'AB Aur',
 'AB Pic b': 'AB Pic',
 'AF Lep b': 'AF Lep',
 'BD+03 2562 b': 'BD+03 2562',
 'BD+14 4559 b': 'BD+14 4559',
 'BD+15 2375 b': 'BD+15 2375',
 'BD+

In [127]:
student_grader.check("Read-in-mapping1", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for Read-in-mapping1...
Great job! You passed all test cases for this question.


True

#### Question 12: Create a `Planet` object for the **fifth** planet in the `planets_1.csv` file.

You **must** access the values in `planets_1.csv` using the `planet_cell` function. Note that the fifth planet would be at **index** 4.

The **attribute** of the `Planet` namedtuple object, the corresponding **column** of the `planets_1.csv` file where the value should be obtained from, and the correct **data type** for the value are listed in the table below:

|Attribute of `Planet` object|Column of `planets_1.csv`|Data Type|
|---------|------|---------|
|`planet_name`|Planet Name|**string**|
|`host_name`| - |**string**|
|`discovery_method`|Discovery Method|**string**|
|`discovery_year`|Discovery Year|**int**|
|`controversial_flag`|Controversial Flag|**bool**|
|`orbital_period`|Orbital Period [days]|**float**|
|`planet_radius`|Planet Radius [Earth Radius]|**float**|
|`planet_mass`|Planet Mass [Earth Mass]|**float**|
|`semi_major_radius`|Orbit Semi-Major Axis [au]|**float**|
|`eccentricity`|Eccentricity|**float**|
|`equilibrium_temperature`|Equilibrium Temperature [K]|**float**|
|`insolation_flux`|Insolation Flux [Earth Flux]|**float**|


The value of the `host_name` attribute is found in `mapping_1.json`.

Points possible: 4.0

In [128]:
# compute and store the answer in the variable 'fifth_planet', then display it
fifth_planet = Planet(
    planet_name = planet_cell(4, 'Planet Name', planets_1_rows), \
    host_name = mapping_1_json.get(planet_cell(4, 'Planet Name', planets_1_rows), None), \
    discovery_method = planet_cell(4, 'Discovery Method', planets_1_rows), \
    discovery_year = planet_cell(4, 'Discovery Year', planets_1_rows), \
    controversial_flag = planet_cell(4, 'Controversial Flag', planets_1_rows), \
    orbital_period = planet_cell(4, 'Orbital Period [days]', planets_1_rows), \
    planet_radius = planet_cell(4, 'Planet Radius [Earth Radius]', planets_1_rows), \
    planet_mass = planet_cell(4, 'Planet Mass [Earth Mass]', planets_1_rows), \
    semi_major_radius = planet_cell(4, 'Orbit Semi-Major Axis [au]', planets_1_rows), \
    eccentricity = planet_cell(4, 'Eccentricity', planets_1_rows), \
    equilibrium_temperature = planet_cell(4, 'Equilibrium Temperature [K]', planets_1_rows), \
    insolation_flux = planet_cell(4, 'Insolation Flux [Earth Flux]', planets_1_rows), \
)
fifth_planet

Planet(planet_name='17 Sco b', host_name='17 Sco', discovery_method='Radial Velocity', discovery_year=2020, controversial_flag=False, orbital_period=578.38, planet_radius=12.9, planet_mass=1373.01872, semi_major_radius=1.45, eccentricity=0.06, equilibrium_temperature=None, insolation_flux=None)

In [129]:
student_grader.check("q12", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q12...
Great job! You passed all test cases for this question.


True

### Project Function 2: `get_planets(planet_file, mapping_file)`: 

This function **must** take in as its input, a **path** to the CSV file `planet_file` which contains data on planets in the same format as `planets_1.csv`, as well as a **path** to the JSON file `mapping_file` which maps planets in `planet_file` to their host star in the same format as `mapping_1.json`. This function **must** return a **list** of `Planet` objects by combining the data in these two files. The `Planet` objects **must** appear in the same order as they do in `planet_file`.

You **must** access the values in `planets_file` using the `planet_cell` function.

You **must not** hardcode the name of the directory `data` into the `get_planets` function. Instead, you must pass it as a part of the arguments `planet_file` and `mapping_file`. In other words, if you want to parse the contents of the files `planets_5.csv` and `mapping_5.json`, your function call must **not** be: `get_planets("planets_5.csv", "mapping_5.json")`. Instead, it must be:

```python
get_planets(os.path.join("data", "planets_5.csv"), os.path.join("data", "mapping_5.json"))
```

For example, when this function is called with the **paths** to the files `planets_1.csv` and `mapping_1.json` as the input, the **list** returned should look like:

```python
[ Planet(planet_name='11 Com b', host_name='11 Com', discovery_method='Radial Velocity', discovery_year=2007, controversial_flag=False, orbital_period=323.21, planet_radius=12.2, planet_mass=4914.89849, semi_major_radius=1.178, eccentricity=0.238, equilibrium_temperature=None, insolation_flux=None),
 Planet(planet_name='11 UMi b', host_name='11 UMi', discovery_method='Radial Velocity', discovery_year=2009, controversial_flag=False, orbital_period=516.21997, planet_radius=12.3, planet_mass=4684.8142, semi_major_radius=1.53, eccentricity=0.08, equilibrium_temperature=None, insolation_flux=None),
 ...]
```

Points possible: 4.0

In [154]:
 # TODO: read planet_file to a list of lists
    # TODO: extract the header and rows from planet_file
    # TODO: read mapping_file to a dictionary
    # TODO: loop through each row in planet_file with indices
def get_planets(planet_file, mapping_file):
    planets_list = []

    planet_csv = process_csv(planet_file)
    planet_header = planet_csv[0]
    planet_rows = planet_csv[1:]

    try:
        mapping_json = read_json(mapping_file)
        
    except json.JSONDecodeError:
        return planets_list
        
    # TODO: create a Planet object (namedTuple) for each row
    # TODO: add each Planet objet to a list
    # TODO: return the list after the end of the loop
    for idx in range(len(planet_rows)):
        try:
            planet_name = planet_cell(idx, 'Planet Name', planet_rows)
            host_name = mapping_json[planet_name]
            discovery_method = planet_cell(idx, 'Discovery Method', planet_rows)
            discovery_year = planet_cell(idx, 'Discovery Year', planet_rows)
            controversial_flag = planet_cell(idx, 'Controversial Flag', planet_rows)
            orbital_period = planet_cell(idx, 'Orbital Period [days]', planet_rows)
            planet_radius = planet_cell(idx, 'Planet Radius [Earth Radius]', planet_rows)
            planet_mass = planet_cell(idx, 'Planet Mass [Earth Mass]', planet_rows)
            semi_major_radius = planet_cell(idx, 'Orbit Semi-Major Axis [au]', planet_rows)
            eccentricity = planet_cell(idx, 'Eccentricity', planet_rows)
            equilibrium_temperature = planet_cell(idx, 'Equilibrium Temperature [K]', planet_rows)
            insolation_flux = planet_cell(idx, 'Insolation Flux [Earth Flux]', planet_rows)
    
            planet = Planet(planet_name, host_name, discovery_method, discovery_year,\
                    controversial_flag, orbital_period, planet_radius, planet_mass,\
                    semi_major_radius, eccentricity, equilibrium_temperature, insolation_flux)
            
            planets_list.append(planet)
            
        except ValueError:
            continue

        except IndexError:
            continue

        except KeyError:
            continue

    return planets_list

In [155]:
student_grader.check("get_planets", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for get_planets...
Great job! You passed all test cases for this question.


True

#### Question 13: What are the **last five** `Planet` objects in the **list** returned by `get_planets` when `planet_file` is `planets_1.csv` and `mapping_file` is `mapping_1.json`?

Your output **must** be a **list** of `Planet` objects.

**Hint:** First, you **must** use the `get_planets` function to parse the data in `planets_1.csv` and `mapping_1.json` and create a **list** of `Planet` objects. Then, you may slice this **list** to get the last five `Planet` objects.

Points possible: 4.0

In [156]:
# compute and store the answer in the variable 'last_five_planets_1', then display it
last_five_planets_1 = get_planets(os.path.join("data", "planets_1.csv"), os.path.join("data", "mapping_1.json"))[-5:]

last_five_planets_1

[Planet(planet_name='Kepler-15 b', host_name='Kepler-15', discovery_method='Transit', discovery_year=2011, controversial_flag=False, orbital_period=4.942782, planet_radius=10.76, planet_mass=209.76, semi_major_radius=0.05714, eccentricity=0.06, equilibrium_temperature=1251.0, insolation_flux=430.68),
 Planet(planet_name='Kepler-1500 b', host_name='Kepler-1500', discovery_method='Transit', discovery_year=2016, controversial_flag=False, orbital_period=15.0330105, planet_radius=1.2, planet_mass=1.87, semi_major_radius=0.1236, eccentricity=0.0, equilibrium_temperature=928.0, insolation_flux=131.82),
 Planet(planet_name='Kepler-1501 b', host_name='Kepler-1501', discovery_method='Transit', discovery_year=2016, controversial_flag=False, orbital_period=14.5564533, planet_radius=1.56, planet_mass=3.05, semi_major_radius=0.1228, eccentricity=0.0, equilibrium_temperature=787.0, insolation_flux=100.0),
 Planet(planet_name='Kepler-1502 b', host_name='Kepler-1502', discovery_method='Transit', discov

In [153]:
student_grader.check("q13", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q13...
Great job! You passed all test cases for this question.


True

#### Question 14: What are the `Planet` objects whose `controversial_flag` attribute is `True` in the **list** returned by `get_planets` when `planet_file` is `planets_2.csv` and `mapping_file` is `mapping_2.json`?

Your output **must** be a **list** of `Planet` objects.

Points possible: 4.0

In [157]:
# compute and store the answer in the variable 'controversial_planets', then display it
controversial_planets = []
planets_2_list = get_planets(os.path.join("data", "planets_2.csv"), os.path.join("data", "mapping_2.json"))

for planet in planets_2_list:
    if planet.controversial_flag == True:
        controversial_planets.append(planet)
        
controversial_planets

[Planet(planet_name='Kepler-452 b', host_name='Kepler-452', discovery_method='Transit', discovery_year=2015, controversial_flag=True, orbital_period=384.843, planet_radius=1.63, planet_mass=3.29, semi_major_radius=1.046, eccentricity=0.0, equilibrium_temperature=265.0, insolation_flux=1.1),
 Planet(planet_name='Kepler-747 b', host_name='Kepler-747', discovery_method='Transit', discovery_year=2016, controversial_flag=True, orbital_period=35.61760587, planet_radius=5.27, planet_mass=24.1, semi_major_radius=0.1916, eccentricity=0.0, equilibrium_temperature=456.0, insolation_flux=10.19),
 Planet(planet_name='V830 Tau b', host_name='V830 Tau', discovery_method='Radial Velocity', discovery_year=2016, controversial_flag=True, orbital_period=4.927, planet_radius=14.0, planet_mass=222.481, semi_major_radius=0.057, eccentricity=0.0, equilibrium_temperature=None, insolation_flux=None),
 Planet(planet_name='nu Oct A b', host_name='nu Oct A', discovery_method='Radial Velocity', discovery_year=2016,

In [158]:
student_grader.check("q14", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q14...
Great job! You passed all test cases for this question.


True

### Data Cleaning 1: Broken CSV rows

Our function `get_planets` works very well so far. However, it is likely that it will not work on all the files in the `data` directory. For example, if you use the function `get_planets` to read the data in `planets_4.csv` and `mapping_4.json`, you will most likely run into an error. **Try it yourself to verify!**

The reason your code likely crashed is because there the file `planets_4.csv` is **broken**. For some reason, several rows in `planets_4.csv` have their data jumbled up. For example, in the **third** row of `planets_4.csv`, we come across this row:

|Planet Name|Discovery Method|Discovery Year|Controversial Flag|Orbital Period [days]|Planet Radius [Earth Radius]|Planet Mass [Earth Mass]|Orbit Semi-Major Axis [au]|Eccentricity|Equilibrium Temperature [K]|Insolation Flux [Earth Flux]|
|-----------|----------------|--------------|------------------|---------------------|----------------------------|------------------------|---------------------------|------------|---------------------------|----------------------------|
47 UMa b|804.08000|1996|0|1078.00000000|13.200|Radial Velocity|2.100000|0.032000||

We can see that for some reason, the value under the column `Discovery Method` is a **number** while the value under the column `Planet Mass [Earth Mass]` is a **string**. It is possible that these two columns of data got *swapped* here, but we cannot be sure about this.

We will call such a **row** in a CSV file where the values under a column do not match the expected format to be a **broken row**. While it is possible to sometimes extract useful data from broken rows, in this project, we will simply **skip** broken rows.

You **must** now go back to your definition of `get_planets` and edit it, so that any **broken rows get skipped**.

**Hints:**

1. The simplest way to recognize if a row is broken is if you run into any **RunTime Errors** when you call the `get_planets` function. So, one simple way to skip bad rows would be to use `try/except` blocks to avoid processing any rows that cause the code to crash; remember **not** to use *bare* `try/except` blocks.
2. There are only **10** broken rows in `planets_4.csv`, and they are all **bunched up** at the very beginning and the very end of the dataset. You can manually **inspect** the **first 10 and last 10** rows, and figure out which of these rows are broken and why.

**Important Warning:** You are **not** allowed to **hardcode** the indices of the broken rows. You may inspect `planets_4.csv` to identify how to tell a **broken row** apart. Therefore, to use the example of the **broken row** above, you **may not** hardcode to skip the **seventh** row of `planets_4.csv`. However, it is **acceptable** to make your function **skip** any row for which the value under the `Planet Name` is not numeric, by observing that this is the reason why the row is broken.

#### Question 15: What are the **last five** `Planet` objects produced by `get_planets` when `planet_file` is `planets_4.csv` and `mapping_file` is `mapping_4.json`?

Your output **must** be a **list** of `Planet` objects.

Points possible: 4.0

In [159]:
# compute and store the answer in the variable 'last_five_planets_4', then display it
last_five_planets_4 = get_planets(os.path.join("data", "planets_4.csv"), os.path.join("data", "mapping_4.json"))[-5:]

last_five_planets_4

[Planet(planet_name='Wolf 1061 d', host_name='Wolf 1061', discovery_method='Radial Velocity', discovery_year=2015, controversial_flag=False, orbital_period=217.21, planet_radius=2.69, planet_mass=7.7, semi_major_radius=0.47, eccentricity=0.55, equilibrium_temperature=None, insolation_flux=0.06),
 Planet(planet_name='YZ Cet c', host_name='YZ Cet', discovery_method='Radial Velocity', discovery_year=2017, controversial_flag=False, orbital_period=3.05989, planet_radius=1.05, planet_mass=1.14, semi_major_radius=0.02156, eccentricity=0.0, equilibrium_temperature=410.0, insolation_flux=4.72),
 Planet(planet_name='pi Men d', host_name='HD 39091', discovery_method='Radial Velocity', discovery_year=2022, controversial_flag=False, orbital_period=124.64, planet_radius=3.72, planet_mass=13.38, semi_major_radius=None, eccentricity=0.22, equilibrium_temperature=None, insolation_flux=None),
 Planet(planet_name='ups And b', host_name='ups And', discovery_method='Radial Velocity', discovery_year=1996, c

In [160]:
student_grader.check("q15", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q15...
Great job! You passed all test cases for this question.


True

### Data Cleaning 2: Broken JSON files

We are now ready to read **all** the files in the `data` directory and create a **list** of `Planet` objects for all the planets in the directory. However, if you try to use `get_planets` on all the planet CSV files and mapping JSON files, you will likely run into another error. **Try it for yourself by calling `get_planets` on all the files in `data`!**

It is likely that your code crashed when you tried to read the data in `planets_5.csv` and `mapping_5.json`. This is because the file `mapping_5.json` is **broken**. Unlike **broken** CSV files, where we only had to skip the **broken rows**, it is much harder to parse **broken JSON files**. When a JSON file is **broken**, we often have no choice but to **skip the file entirely**.

You **must** now go back to your definition of `get_planets` and edit it, so that if the JSON file is **broken**, then the file is completely skipped, and only an **empty list** is returned.

**Important Warning:** You are **not** allowed to **hardcode** the name of the files to be skipped. You **must** use `try/except` blocks to determine whether the JSON file is **broken** and skip the file if it is.

**Hint:** You might also want to review the **Project Requirements** at the start of this project, before you use `try/except`.

### Project Data Structure 2: `planets_list`

You are now ready to read all the data about the planets stored in the `data` directory. You **must** now create a **list** containing `Planet` objects by parsing the data inside the files `planets_1.csv`, ..., `planets_5.csv` and `mapping_1.json`, ..., `mapping_5.json`.

You **must** skip any **broken rows** in the CSV file, and also completely skip any **broken JSON files**. However, you are **not** allowed to **hardcode** the file you need to skip. You **must** call `get_planet` on **all** 5 pairs of files to answer this question.

You **must** use the `get_planets` function on each of the five pairs of files in the `data` directory to create `planets_list`.

**Warning:** Recall that the ordering of the files returned by the `os.listdir` function **depends on the operating system**. So, you need to be careful if your code relies on the ordering of the **list** returned by this function. One way to avoid any issues here would be to **sort** the **list** first, so that the ordering is identical across all operating systems.

Points possible: 4.0

In [164]:
# define the variable 'planets_list' here,
# but do NOT display the variable at the end
planets_paths = sorted([path for path in file_paths if "planets" in path])
json_mapping_paths = sorted([path for path in file_paths if path.endswith(".json")])

planets_list = []
for i in range(len(planets_paths)):
    lst = get_planets(planets_paths[i], json_mapping_paths[i])
    planets_list.extend(lst)

In [165]:
student_grader.check("planets_list", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for planets_list...
Great job! You passed all test cases for this question.


True

#### Question 16: What is the output of `planets_list[5020:5025]`?

Your output **must** be a **list** of `Planet` objects.

**Hint:** If you did not get the right answer here, it is possible that you did not read the files in the correct **order**. In `planets_list`, the planets from `planets_1.csv` should appear first (in the order that they appear in the dataset), followed by the planets from `planets_2.csv`, `planets_3.csv`, `planets_4.csv`, and `planets_5.csv`.

Points possible: 4.0

In [166]:
# compute and store the answer in the variable 'planets_5020_5025', then display it
planets_5020_5025 = planets_list[5020:5025]

planets_5020_5025

[Planet(planet_name='Kepler-9 c', host_name='Kepler-9', discovery_method='Transit', discovery_year=2010, controversial_flag=False, orbital_period=38.9853, planet_radius=8.08, planet_mass=29.9, semi_major_radius=0.227, eccentricity=0.06691, equilibrium_temperature=523.0, insolation_flux=18.9),
 Planet(planet_name='Kepler-9 d', host_name='Kepler-9', discovery_method='Transit', discovery_year=2010, controversial_flag=False, orbital_period=1.592851, planet_radius=1.64, planet_mass=8.41466, semi_major_radius=0.0273, eccentricity=0.0, equilibrium_temperature=2026.0, insolation_flux=1339.66),
 Planet(planet_name='Kepler-92 b', host_name='Kepler-92', discovery_method='Transit', discovery_year=2013, controversial_flag=False, orbital_period=13.749, planet_radius=3.51, planet_mass=64.3, semi_major_radius=0.122268, eccentricity=0.17, equilibrium_temperature=975.0, insolation_flux=257.78),
 Planet(planet_name='Kepler-92 c', host_name='Kepler-92', discovery_method='Transit', discovery_year=2013, con

In [167]:
student_grader.check("q16", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q16...
Great job! You passed all test cases for this question.


True

#### Question 17: How many planets in `planets_list` were discovered in the year *2023*?

Your output **must** be an **integer**.

Points possible: 4.0

In [168]:
# compute and store the answer in the variable 'planets_disc_2023', then display it
planets_disc_2023 = 0

for planet in planets_list:
    if planet.discovery_year == 2023:
        planets_disc_2023 += 1

planets_disc_2023

289

In [169]:
student_grader.check("q17", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q17...
Great job! You passed all test cases for this question.


True

#### Question 18: Find the `Star` object around which the `Planet` named *TOI-2202 c* orbits.

Your output **must** be a `Star` object.

**Hint:** You **must** first find the `Planet` object with the `planet_name` *TOI-2202 c* and then use the `host_name` attribute to identify the name of the star around which the planet orbits. Then, you can get the `Star` object using the `stars_dict` **dictionary** defined above.

You **must** exit the loop once you find the first planet with the target name.

Points possible: 4.0

In [170]:
# compute and store the answer in the variable 'toi_2022_c_star', then display it
for planet in planets_list:
    if planet.planet_name == "TOI-2202 c":
        host_name = planet.host_name
        break

toi_2022_c_star = stars_dict[host_name]

toi_2022_c_star

Star(spectral_type='K8V', stellar_effective_temperature=5144.0, stellar_radius=0.79, stellar_mass=0.82, stellar_luminosity=-0.401, stellar_surface_gravity=4.55, stellar_age=7.48)

In [171]:
student_grader.check("q18", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q18...
Great job! You passed all test cases for this question.


True

#### Question 19: Find the **average** `planet_radius` (in units of the radius of the Earth) of the planets that orbit stars with `stellar_radius` more than *10* (i.e. more than *10* times the radius of the Sun).

Your output **must** be a **float**. You **must** skip any `Planet` objects with **missing** `planet_radius` data and any `Star` objects with **missing** `stellar_radius` data.

Points possible: 4.0

In [183]:
# compute and store the answer in the variable 'avg_planet_radius_big_stars', then display it
big_stars = []

for star in stars_dict:
    stellar_radius = stars_dict[star].stellar_radius
    if stellar_radius == None:
        continue
    elif stellar_radius > 10:
        big_stars.append(star)

total_planet_radius_big_stars = 0
planet_count = 0

for planet in planets_list:
    if planet.host_name in big_stars:
        if planet.planet_radius != None:
            total_planet_radius_big_stars += planet.planet_radius
            planet_count += 1

avg_planet_radius_big_stars = total_planet_radius_big_stars / planet_count

avg_planet_radius_big_stars

12.888118811881188

In [184]:
student_grader.check("q19", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q19...
Great job! You passed all test cases for this question.


True

#### Question 20: Find all the `Planet` objects that orbit the **youngest** `Star` object.

Your output **must** be a **list** of `Planet` objects (even if there is **only one** `Planet` in the list). The age of a `Star` can be found from its `stellar_age` column. You do **not** have to worry about any ties. There is a **unique** `Star` in the dataset which is the youngest star.

Points possible: 4.0

In [175]:
# compute and store the answer in the variable 'youngest_star_planets', then display it
youngest_star = None
youngest_star_age = None

for star in stars_dict:
    star_age = stars_dict[star].stellar_age
    if star_age == None:
        continue
    elif youngest_star == None or youngest_star_age > star_age:
        youngest_star = star
        youngest_star_age = star_age

youngest_star_planets = []

for planet in planets_list:
    if planet.host_name == youngest_star:
        youngest_star_planets.append(planet)

youngest_star_planets

[Planet(planet_name='Kepler-1663 b', host_name='Kepler-1663', discovery_method='Transit', discovery_year=2020, controversial_flag=False, orbital_period=17.6046, planet_radius=3.304, planet_mass=10.9, semi_major_radius=0.1072, eccentricity=0.0, equilibrium_temperature=362.0, insolation_flux=4.07)]

In [176]:
student_grader.check("q20", should_get_llm_feedback=False)

Make sure you saved the notebook before running this cell. Running check for q20...
Great job! You passed all test cases for this question.


True

### Submission

Make sure you have run all cells in your notebook in order before submitting on Gradescope. Your notebook should not contain any uncaught Exceptions, otherwise the Gradescope autograder will not give you any points.